"""Additional article-specific reading, grounded in the sources linked per guide."""

EXPANSIONS = {
    "caniche": [
        ("Armar un cuidado del pelo que no sea una batalla", "Antes de cepillar, separá el manto con los dedos y revisá detrás de las orejas, en las axilas y bajo el arnés, donde el roce favorece los nudos. Si un mechón está muy tirante o pegado a la piel, no lo arranques ni uses tijeras cerca del cuerpo: pedí ayuda a quien se encargue de su arreglo. Una sesión corta y tranquila, con pausas y un premio al terminar, suele ser más sostenible que esperar a que el pelo esté muy enredado."),
        ("Cambiar la rutina cuando cambia el perro", "Un caniche joven quizá disfrute aprender una señal nueva durante el paseo; uno mayor puede preferir explorar despacio y descansar más. La clave es mirar su respuesta: si se detiene, evita que lo toquen, deja de saltar como antes o ya no acepta el cepillado, puede haber dolor u otra molestia. Llevá esos ejemplos concretos a la consulta. La raza orienta algunas preguntas, pero la edad, el tamaño y el estado de salud son los que ajustan el plan."),
    ],
    "corgi": [
        ("Una semana que combine movimiento y pausa", "No hace falta que cada salida sea intensa. Repartí caminatas, tiempo para olfatear y juegos tranquilos durante la semana; observá si al día siguiente se mueve con la misma comodidad. En casa, una superficie que no resbale puede facilitarle levantarse y jugar. Si una actividad nueva lo deja rígido o modifica su marcha, suspendela y consultá antes de insistir. Un corgi activo también necesita recuperar energía y dormir sin interrupciones."),
        ("Medir los extras ayuda más que adivinarlos", "Durante unos días, anotá la cantidad de alimento, premios de entrenamiento y bocados que recibe de otras personas. Esa fotografía completa permite conversar sobre su condición corporal con datos reales. Si usás parte de su ración diaria para enseñarle algo, esa comida también cuenta; no es necesario sumar siempre una golosina extra. Un descenso de peso, si hiciera falta, debe planearse con un veterinario para conservar músculo y no convertir la comida en una restricción improvisada."),
    ],
    "perro-salchicha": [
        ("El dolor de espalda puede verse de distintas maneras", "No siempre aparece después de una caída. Puede que se niegue a subir al sillón, camine encorvado, tiemble, grite al moverlo o mantenga una postura inusual. La enfermedad de los discos intervertebrales afecta con especial frecuencia a los dachshunds, pero sólo una evaluación permite saber qué ocurre en ese perro. Si arrastra una pata, pierde fuerza o no controla la orina, la consulta es urgente. Esperar para ver si mejora puede dejar que el problema avance."),
        ("Qué hacer mientras organizás la atención", "Si sospechás dolor de columna, reducí los movimientos bruscos y evitá juegos, saltos o escaleras hasta hablar con un veterinario. Para trasladarlo, sostené el pecho y la parte trasera de manera estable; una transportadora apropiada puede ayudar si el perro la tolera. Contá cuándo empezó, qué cambió y si puede caminar y orinar. No le des analgésicos de personas: algunos son peligrosos para los perros y además pueden dificultar la evaluación."),
    ],
    "golden-retriever": [
        ("Hacer espacio para un perro grande", "Una cama donde pueda estirarse, un lugar fresco para descansar y un piso que no lo haga patinar ayudan a organizar la casa. Si todavía está creciendo, evitá convertir las salidas en pruebas de resistencia: el tipo y la intensidad de ejercicio se ajustan con su veterinario. En un adulto, también conviene alternar actividad física con búsqueda de objetos o juegos tranquilos. Mirá cómo se recupera después del paseo, no sólo cuánto entusiasmo mostró al salir."),
        ("El cepillado también sirve para conocerlo", "Al separar el pelo podés encontrar zonas húmedas, irritación, bultos, heridas o parásitos que el manto escondía. Prestá atención a la piel bajo el collar y detrás de las orejas; si hay mal olor, dolor o secreción en el oído, consultá antes de aplicar gotas. Un registro breve de hallazgos y la fecha en que aparecieron ayuda mucho más que intentar describir de memoria algo que ya cambió."),
    ],
    "bulldog-frances": [
        ("El ruido no mide por sí solo la salud respiratoria", "En perros de cara corta, respirar con esfuerzo durante el descanso, no poder dormir cómodos o tardar demasiado en recuperarse tras una actividad son motivos para pedir una evaluación. Que un sonido sea frecuente en la raza no significa que deba aceptarse como bienestar normal. Podés grabar un video corto de su respiración mientras duerme o después de caminar, sin provocarle esfuerzo para obtenerlo. Esa observación ayuda al veterinario a entender cómo se encuentra fuera del consultorio."),
        ("Planear el día en torno a su tolerancia", "En verano, probá salidas breves cuando baja la temperatura y dejá una alternativa de juego tranquilo adentro. Evitá la humedad y el calor intenso; tené sombra, agua y un lugar ventilado para volver. Los pliegues de la cara deben mantenerse limpios y secos, pero si la piel está roja o duele, necesitás orientación antes de usar productos. Si aparece dificultad marcada para respirar, encías azuladas o colapso, buscá atención de urgencia."),
    ],
    "dalmata": [
        ("Por qué mirar de cerca la orina", "Los dálmatas tienen una particularidad hereditaria en el metabolismo del ácido úrico que aumenta el riesgo de ciertos cálculos urinarios. Eso no significa que cada uno vaya a desarrollarlos, ni justifica cambiar la dieta por cuenta propia. Sí vuelve útil registrar si orina más veces, hace esfuerzo, deja pequeñas cantidades o muestra dolor. Si intenta orinar y no puede, buscá ayuda inmediata. El veterinario puede decidir qué estudios y qué pauta de hidratación o alimentación necesita ese individuo."),
        ("La audición también forma parte del perfil", "La sordera congénita es más frecuente en esta raza que en muchas otras. Si un cachorro no responde a sonidos, no lo atribuyas a terquedad: consultá por una evaluación auditiva. Un perro con pérdida de audición puede aprender señales visuales y convivir bien, pero necesita que las personas eviten sorprenderlo y que las salidas se organicen con seguridad. Saberlo temprano permite adaptar la comunicación sin retarlo por algo que no escucha."),
    ],
    "husky-siberiano": [
        ("Un paseo útil no siempre es el más largo", "En días templados, alterná caminar con tiempo de olfato, cambios de recorrido y pequeñas consignas. Cuando hace calor, reducí la duración y elegí primeras o últimas horas del día; el jadeo intenso, la desorientación o la debilidad cambian el plan por una consulta urgente. Llevá agua y buscá sombra. Su doble manto requiere cepillado y control de piel: raparlo sin una indicación profesional no resuelve por sí solo el riesgo de sobrecalentamiento."),
        ("Preparar la casa para un explorador", "Revisá puertas, rejas y zonas desde las que pueda escaparse, incluso si habitualmente vuelve al llamado. Identificación visible y datos de contacto actualizados importan tanto como una correa bien ajustada. Dentro de casa, ofrecerle juguetes para buscar comida o tareas sencillas puede ocuparlo cuando salir no es conveniente. Si aparece destructividad nueva, evaluá primero si hay cambios en la rutina, falta de actividad, estrés o una molestia física."),
    ],
    "shiba-inu": [
        ("Una presentación respetuosa vale más que muchas forzadas", "Si llega una visita o conoce otro perro, permitile observar a distancia y retirarse. No hace falta que acepte una caricia ni que juegue para que el encuentro salga bien. Reforzá con algo que valore cuando elige acercarse tranquilo; si se pone rígido, fija la mirada o se aleja, dale espacio. Estas señales no se resuelven sujetándolo para que «se acostumbre». Un profesional de comportamiento puede ayudar cuando la tensión se repite."),
        ("La seguridad no depende de una sola orden", "La respuesta al llamado se practica en entornos fáciles antes de usarla en sitios con distracciones. Aun con buen aprendizaje, la correa y los espacios cerrados siguen siendo importantes si hay tránsito, animales sueltos o posibilidad de fuga. Un arnés que ajuste bien reduce el riesgo de que se zafe sin impedirle caminar. Si rechaza de pronto un manejo que antes toleraba, pensá también en dolor y consultá."),
    ],
    "beagle": [
        ("Una búsqueda fácil para hacer en casa", "Podés esconder pequeñas porciones de su alimento habitual en lugares accesibles y dejar que las encuentre con la nariz. Empezá con escondites visibles, supervisá para que no trague objetos y contá esa comida dentro de la ración del día. La actividad termina cuando todavía la disfruta; no hace falta complicarla hasta frustrarlo. Este tipo de juego sirve en días en que un paseo largo no es posible, pero no reemplaza la salida para explorar el entorno."),
        ("Anticipar lo que puede distraerlo afuera", "Antes de cruzar una calle o abrir una puerta, asegurá correa y arnés. Si encuentra un rastro interesante, darle un momento para investigarlo en un sitio seguro suele funcionar mejor que tironear continuamente. Practicá volver hacia vos en lugares tranquilos y premiá cada respuesta. Un beagle no es «desobediente» por olfatear: usar esa motivación ayuda a diseñar salidas más agradables y seguras para ambos."),
    ],
    "pitbull": [
        ("Leer al perro antes que a la etiqueta", "Algunos perros se entusiasman con visitas; otros necesitan espacio. Observá su cuerpo, la facilidad con la que vuelve a relajarse y las situaciones que le cuestan. No obligues encuentros con personas o animales para demostrar que es sociable. Si aparece miedo, rigidez o conflicto frecuente, una evaluación de salud y apoyo profesional en comportamiento pueden orientar el trabajo. Los métodos que provocan dolor o miedo pueden empeorar el problema y dañan la confianza."),
        ("Un plan realista para el movimiento", "Los juegos de fuerza y la actividad intensa se adaptan a la edad y condición física, especialmente si lleva tiempo sin ejercitarse. Alterná caminatas, búsqueda de comida y descanso; registrá si queda dolorido o cojea después. En la consulta se puede revisar peso, piel y articulaciones y ajustar la rutina. Llevar una lista de alimentos, premios y cambios observados permite salir con decisiones concretas, sin suponer que todos los perros de aspecto parecido necesitan lo mismo."),
    ],
    "perro-mestizo": [
        ("Las primeras semanas después de llegar", "Si acaba de ser adoptado, mantené horarios simples para comida, descanso y salidas. Dejá que conozca la casa por partes y que elija dónde descansar; el entusiasmo por mostrarle todo puede abrumarlo. Identificá qué situaciones lo relajan y cuáles lo ponen en alerta. Si convivirá con otros animales, prepará presentaciones graduales y recursos separados. Una conducta de los primeros días no define su personalidad para siempre: el contexto y el tiempo importan."),
        ("Convertir los antecedentes incompletos en un plan", "No saber la edad exacta o qué vacunas recibió no impide comenzar a cuidarlo. Llevá los datos que tengas, aunque sean fotos de una libreta, y conversá sobre evaluación clínica, prevención de parásitos, alimentación e identificación. Si hay diarrea, tos, lesiones o decaimiento, mencioná los síntomas antes de acercarlo a otros animales. Un plan individual basado en su estado actual es más útil que adivinar su mezcla de razas."),
    ],
    "chihuahua": [
        ("Una casa a su escala", "Mirá desde su altura si hay huecos por los que pueda caer, escalones que le cuesten o zonas donde otros animales lo puedan pisar sin querer. Una cama abrigada y un refugio tranquilo le permiten retirarse cuando necesita descanso. Enseñá a las visitas a esperar que se acerque en vez de tomarlo en brazos. Respetar esa elección no lo «malcría»: reduce situaciones de miedo y ayuda a que el contacto sea seguro."),
        ("No dejar que el tamaño oculte molestias", "Un perro pequeño puede seguir caminando aunque le duela la boca o una articulación. Registrá si mastica de un solo lado, evita subir, tose, tiembla más de lo habitual o se resiste a que lo levanten. Una revisión puede separar conducta, temperatura y problemas de salud. El peso también merece seguimiento: unos gramos de premios tienen más efecto relativo en un cuerpo chico, así que conviene acordar porciones con el veterinario."),
    ],
}

EXPANSIONS.update({
    "gato-primer-ano": [
        ("Llegar a casa sin apurarlo", "Un gatito recién llegado puede esconderse, observar y salir cuando el ambiente se aquieta. Dejá el transportín abierto en su habitación inicial, con agua, comida, un escondite y el arenero lejos de los platos. Mostrale la casa de forma gradual y comprobá que ventanas y balcones estén protegidos antes de permitirle explorar. Si hay otros animales, intercambiar olores y separar recursos al principio suele ser más amable que un encuentro de golpe. Evitá usar las manos como juguete."),
        ("Qué conviene registrar para el primer control", "Anotá edad estimada, origen, alimento actual, apetito, materia fecal y cualquier constancia de vacunas o desparasitación. También sirve contar si hay otros gatos en casa o acceso al exterior. Con esa información, el veterinario puede diseñar un calendario de prevención y conversar sobre identificación y castración según el caso. Si no come, está muy quieto o presenta vómitos o diarrea, no esperes a la visita de rutina: los gatitos pueden descompensarse con rapidez."),
    ],
    "gato-de-interior": [
        ("Separar recursos para dar opciones", "La comida, el agua, los lugares de descanso, los rascadores y los areneros funcionan mejor cuando el gato puede acceder a ellos sin cruzarse obligadamente con otro animal. En hogares con varios gatos, repartirlos por distintos sectores reduce competencia. Un estante alto o una caja de cartón pueden ofrecer refugio sin ocupar mucho lugar. Observá cuál usa y cuál evita; no todos prefieren la misma altura ni el mismo tipo de escondite."),
        ("Juego que respete su manera de cazar", "Una caña o juguete que se aleja, se esconde y vuelve a aparecer puede despertar más interés que moverlo sin pausa delante de su cara. Permitile alcanzarlo alguna vez y terminá con calma; si usás comida como cierre, contala dentro de su ración. Cambiá los juguetes disponibles cada cierto tiempo y revisá que no haya hilos o piezas que pueda tragar. Si deja de jugar de repente, antes de comprar algo nuevo conviene descartar dolor o enfermedad."),
    ],
    "gato-agua-y-arenero": [
        ("Preparar un baño que quiera usar", "Elegí un arenero lo bastante amplio para que gire, en un sitio accesible y con poca circulación. Retirá los desechos cada día y observá si prefiere una caja abierta, una arena sin perfume o una ubicación distinta. En una casa con varios gatos, ofrecer más de una caja en lugares separados puede evitar que uno bloquee el acceso del otro. Si de pronto orina afuera, no lo castigues: primero hay que descartar dolor o enfermedad."),
        ("Cuándo es una urgencia y qué contar", "Un gato que entra reiteradamente al arenero, hace fuerza y no logra orinar necesita atención inmediata, especialmente si es macho. También importan el dolor, sangre, vómitos o decaimiento. No intentes apretarle el abdomen ni esperes al día siguiente. Si podés, anotá la última vez que lo viste orinar normalmente, cambios de agua y comida, y cualquier episodio previo. Esos datos ayudan al equipo veterinario; no sustituyen el traslado."),
    ],
    "gato-mayor": [
        ("Pequeñas adaptaciones que preservan su autonomía", "Si ya no salta al sitio donde solía descansar, acercá un escalón estable o una rampa de pendiente suave y comprobá que no resbale. Un arenero de entrada baja y los platos en un lugar fácil de alcanzar pueden evitar esfuerzos innecesarios. Mantené opciones de refugio y juego: envejecer no elimina la necesidad de elegir. Antes de cambiar toda la casa, observá qué recorrido dejó de hacer y adaptá ese punto concreto."),
        ("Los cambios lentos también cuentan", "Pérdida de peso, más sed, mal aliento, menos aseo, dificultad para saltar o maullidos nuevos pueden aparecer de a poco. Llevar un registro mensual de peso y una lista breve de hábitos facilita detectar una tendencia. No asumas que es «cosa de la edad»: por ejemplo, el dolor articular puede hacer que un gato use menos ciertas zonas sin mostrar una cojera evidente. En consulta pueden decidir si hacen falta examen bucal, evaluación de movilidad u otros estudios."),
    ],
    "loro": [
        ("Primero, saber qué especie vive con vos", "«Loro» reúne aves muy diferentes en tamaño, longevidad, dieta y necesidad de espacio. Anotá su especie, edad aproximada, procedencia y alimento habitual antes de cambiar la rutina. Una dieta basada sólo en semillas puede dejar nutrientes esenciales sin cubrir, pero tampoco conviene reemplazarla de un día para otro si el ave no reconoce otro alimento. Un veterinario con experiencia en aves puede ayudar a planear una transición segura y recomendar controles adecuados para esa especie."),
        ("Una casa segura fuera de la jaula", "Si sale a explorar, cerrá ventanas, apagá ventiladores de techo y evitá acceso a cocina, cables y objetos pequeños que pueda romper o ingerir. Supervisá la interacción con perros y gatos aunque parezcan tranquilos. Ofrecé materiales y juguetes seguros para manipular y rotalos sin cambiar todo de golpe. El tiempo de descanso sin interrupciones también importa. Si deja de comer, permanece erizado o respira con esfuerzo, buscá atención aviar sin esperar a que se note muy enfermo."),
    ],
    "ninfa": [
        ("Moverse con seguridad", "Una ninfa necesita espacio para extender las alas, cambiar de percha y explorar. Revisá que las perchas no tengan todas el mismo diámetro y que los recipientes de comida y agua no queden bajo una zona donde caen heces. Antes de permitir vuelo en una habitación, cerrá puertas y ventanas y retirale acceso a ventiladores, agua abierta y superficies calientes. No asumas que un ala recortada hace imposible un accidente: la supervisión sigue siendo necesaria."),
        ("Observar más que el canto", "Aprendé cómo come, se posa y se acicala habitualmente. Una ninfa que pasa horas esponjada, duerme más, baja al suelo de la jaula, cambia sus heces o mueve la cola al respirar necesita una evaluación veterinaria. Las aves pueden ocultar signos de enfermedad, por lo que una alteración pequeña de su rutina merece atención. Evitá iniciar vitaminas o antibióticos por tu cuenta y llevá a la consulta una lista de alimentos, fotos del ambiente y cambios recientes."),
    ],
    "periquito": [
        ("La jaula es una parte de su mundo", "Ubicala donde tenga luz y actividad diurna, pero pueda dormir sin ruido ni sobresaltos. Necesita perchas estables, recipientes limpios y oportunidades seguras de moverse; llenar cada centímetro con juguetes le quita espacio útil. Cuando salga, cerrá puertas y ventanas y supervisá ventiladores, espejos y otros animales. Si vive con otro periquito, observá que ambos puedan acceder a comida y descanso sin quedar desplazados. La convivencia no se resuelve sólo con poner dos aves juntas."),
        ("Una transición alimentaria se acompaña", "Si sólo elige semillas, conversá con un veterinario aviar sobre opciones apropiadas para periquitos y un cambio gradual. Retirar de golpe el alimento conocido puede hacer que coma menos sin que se note. Mirá a diario si realmente ingiere comida, cómo son sus heces y si mantiene la actividad habitual. Evitá medicar el agua sin indicación: así es difícil saber cuánto recibe. Una pérdida de apetito o un ave quieta y esponjada justifican consulta pronta."),
    ],
    "canario": [
        ("Un ambiente que no lo sobresalte", "Elegí un sitio ventilado, lejos de humos, corrientes intensas y cambios bruscos de temperatura. La jaula debe permitir moverse entre perchas sin que la cola roce continuamente los barrotes. Mantené comida y agua limpias y retirale alimentos frescos antes de que se deterioren. Si hay otras aves, observá si puede descansar y comer sin conflictos; la convivencia depende de los individuos y del espacio disponible."),
        ("Escuchar y mirar a la vez", "El canto puede variar con la muda, la estación o el ambiente, así que no es un diagnóstico por sí solo. Lo preocupante es el conjunto: menos actividad, plumaje erizado durante mucho tiempo, cambios en heces, apetito o respiración. Anotá desde cuándo lo notaste y, si es posible, grabá un video breve sin molestarlo. Las aves tienden a ocultar enfermedad; una evaluación temprana es más útil que esperar a que deje de posarse o comer."),
    ],
})

EXPANSIONS.update({
    "conejo": [
        ("Comer heno es una parte central del cuidado", "El heno de buena calidad debe estar disponible todo el tiempo: aporta fibra y favorece el desgaste normal de los dientes. Revisá que huela bien y no tenga humedad ni moho. Una dieta centrada en zanahorias, frutas o premios no cubre sus necesidades. Si hoy rechaza el heno, no lo dejes sin comer para obligarlo: consultá, porque puede haber un problema dental u otra causa. Los cambios de alimento conviene planearlos de manera gradual."),
        ("Espacio y compañía también son salud", "Un conejo necesita poder dar saltos, estirarse, esconderse y explorar, no sólo entrar en su refugio. Prepará un área segura con suelo apropiado, protección de cables y acceso continuo a agua, heno y descanso. La compañía de otro conejo compatible suele ser importante, pero presentarlos de golpe puede terminar en peleas; pedí orientación para hacerlo bien. Si come menos, deja de producir heces o permanece encorvado, buscá atención veterinaria pronto."),
    ],
    "cobayo": [
        ("La vitamina C no se improvisa", "Los cobayos no producen su propia vitamina C y deben obtenerla de una dieta adecuada. Los pellets formulados pueden perder vitamina C con el tiempo, la luz o la humedad; por eso importa cómo se guardan y desde cuándo están abiertos. El heno debe estar siempre disponible y las verduras apropiadas se eligen según su situación. Evitá calcular suplementos o dosis por tu cuenta. Si pierde apetito, baja de peso o camina distinto, una consulta puede detectar a tiempo un problema nutricional o dental."),
        ("Un hogar para esconderse y convivir", "Necesitan un piso firme, refugios y espacio para caminar sin quedar acorralados. En una convivencia de varios cobayos, ofrecé más de un lugar para esconderse y comer; vigilá que uno no impida el acceso del otro. No uses rejillas como suelo principal, porque pueden lastimarles las patas. Registrá peso y apetito con regularidad: un animal pequeño puede parecer activo mientras empieza a comer menos. La pérdida de apetito merece atención rápida, no una espera de varios días."),
    ],
    "hamster": [
        ("Preparar un lugar donde pueda excavar", "Una base sólida y una capa profunda de material de cama seguro le permiten cavar y construir un nido. Evitá algodón o materiales fibrosos que puedan enredarse en sus patas. La rueda debe tener superficie continua y tamaño suficiente para que pueda correr sin doblar excesivamente el cuerpo. Sumá escondites y túneles sin perder superficie de suelo. Revisá cierres y espacios por donde podría escaparse: un hámster puede desaparecer con facilidad en una casa."),
        ("Respetar el horario del animal", "No lo despiertes para que interactúe. Acercá la mano despacio cuando está activo, dejá que investigue y sostenelo cerca de una superficie segura por si se mueve. En general, un hámster adulto vive mejor sin compañeros de jaula; juntar individuos puede provocar peleas graves. Si guarda comida, distinguí esa conducta normal de dejar de comer o perder peso. Consultá si hay secreción, respiración ruidosa, diarrea o una reducción marcada de actividad en su horario habitual."),
    ],
    "tortuga": [
        ("El nombre de la especie cambia todo el plan", "Una tortuga terrestre no necesita el mismo recinto ni come lo mismo que una acuática. Antes de comprar un terrario, averiguá la especie exacta y su tamaño adulto; pedí ayuda a un veterinario familiarizado con reptiles para definir temperatura, humedad, luz UVB, agua y dieta. Medí las condiciones del ambiente con instrumentos adecuados en vez de adivinarlas al tacto. Una lámpara encendida no garantiza por sí sola que el hábitat cumpla lo que el animal necesita."),
        ("Observar al animal y al ambiente juntos", "Anotá actividad, apetito, aspecto de ojos y caparazón, heces y temperatura de las zonas del recinto. Si deja de comer, respira con dificultad, mantiene los ojos cerrados o tiene lesiones en el caparazón, buscá una evaluación. Llevá fotos del hábitat y la lista del equipo y alimentos usados: muchos problemas de reptiles se entienden mejor al revisar su entorno. Lavate las manos después de manipular la tortuga o limpiar su espacio, una precaución importante por el riesgo de Salmonella."),
    ],
})

EXPANSIONS.update({
    "vacunas-perros-gatos": [
        ("Por qué no hay un calendario idéntico para todos", "Las guías de WSAVA distinguen vacunas esenciales para perros y gatos de otras indicadas según el lugar y el modo de vida. La edad, antecedentes, viajes, convivencia con otros animales y situación sanitaria local cambian la conversación. En cachorros y gatitos, la protección recibida de la madre puede interferir con una dosis temprana, por eso se programa una serie y no una sola aplicación. No copies un calendario encontrado en internet ni supongas que una libreta incompleta equivale a estar protegido."),
        ("Qué llevar y qué preguntar en la visita", "Llevá la libreta sanitaria o fotos de registros anteriores, aun si están incompletos. Contá si tu animal sale, convive con otros, viaja, tiene enfermedades o recibió alguna reacción después de una vacuna. Pedí que te expliquen qué se aplicó, para qué sirve y cuándo corresponde la siguiente decisión. Guardá la constancia en un lugar fácil de encontrar: ayuda cuando cambiás de veterinaria, dejás al animal al cuidado de otra persona o necesitás acreditar una vacunación."),
        ("Después de vacunar", "Puede haber una molestia leve y pasajera en el lugar de aplicación o menos actividad por un corto tiempo. Preguntá antes de salir qué signos esperar y a quién llamar si aparecen. Dificultad para respirar, hinchazón de la cara, debilidad marcada o vómitos repetidos requieren atención inmediata. No des medicación humana para «prevenir» molestias. La vacunación es una parte de la prevención; el examen clínico permite detectar otras necesidades que una inyección no resuelve."),
    ],
    "salud-dental-perros-gatos": [
        ("El mal aliento no es sólo un detalle", "Olor persistente, encías rojas, sarro visible, babeo, masticar de un solo lado o dejar caer comida pueden indicar un problema. Muchos animales siguen comiendo pese al dolor; esperar a que rechacen el alimento puede retrasar la consulta. No intentes raspar sarro en casa con objetos ni uses pasta dental humana. Pedí que revisen boca, dientes y encías en los controles, incluso si no viste una lesión evidente."),
        ("Cómo empezar una higiene posible", "Primero acostumbralo a que le toquen suavemente el hocico y los labios, con sesiones muy breves. Después, con orientación profesional, podés introducir cepillo y pasta formulados para animales. Si se resiste o muestra dolor, detenete y consultá; la higiene no debe convertirse en una pelea. Los premios o juguetes dentales pueden formar parte del plan, pero no reemplazan la evaluación ni la limpieza profesional cuando hace falta. La AVMA explica que limpiar sólo lo visible no permite revisar ni tratar debajo de la encía."),
    ],
    "peso-saludable-mascotas": [
        ("Qué aporta una evaluación corporal", "Dos animales con el mismo peso pueden tener cuerpos muy distintos. Por eso el veterinario combina balanza, palpación de costillas, cintura y masa muscular, además de revisar edad y enfermedades. Las herramientas de condición corporal de WSAVA ayudan a seguir cambios entre controles. Una foto tomada siempre desde el mismo ángulo y un registro de peso pueden mostrar tendencias, pero no reemplazan esa evaluación. La pérdida de peso no buscada también merece consulta."),
        ("Un plan que toda la casa pueda seguir", "Anotá durante una semana alimento principal, premios, restos compartidos, suplementos y quién se los ofrece. Decidir una sola ración diaria, medirla y repartirla entre las personas evita extras invisibles. Si el animal pide comida con frecuencia, el juego y la búsqueda pueden ofrecer interacción sin sumar calorías, según su salud. No reduzcas porciones drásticamente ni cambies a una dieta casera sin planificación: una mejora segura necesita tiempo, seguimiento y ajustes individuales."),
    ],
    "golpe-de-calor-mascotas": [
        ("Prevenir también implica mirar el suelo y el encierro", "Un paseo al sol puede calentar veredas y asfalto mucho más que el aire. Elegí horarios frescos y permití pausas en sombra; llevá agua, especialmente si el animal es mayor, tiene sobrepeso o respira con dificultad. Nunca lo dejes en un vehículo estacionado: una ventana abierta no lo vuelve seguro. También pueden calentarse galerías, patios o habitaciones mal ventiladas. Revisá que siempre pueda retirarse a un lugar fresco."),
        ("Qué hacer si sospechás sobrecalentamiento", "Sacalo del calor y contactá una guardia veterinaria. Empezá a enfriarlo de inmediato mojándolo con agua más fría que su cuerpo y usando ventilación mientras organizás el traslado; no esperes a que «se le pase». En perros conscientes y sanos, las recomendaciones actuales también contemplan la inmersión en agua fría cuando puede hacerse de forma segura. Jadeo extremo, vómitos, tambaleo, desorientación o colapso son señales de emergencia. Aunque vuelva a parecer alerta, el golpe de calor puede causar daño que no se ve en casa y requiere evaluación profesional."),
    ],
    "parvovirus-en-perros": [
        ("Por qué un cachorro puede empeorar rápido", "El virus afecta el intestino y puede causar vómitos, diarrea, deshidratación y un estado general muy comprometido. No todos los perros tienen diarrea con sangre desde el comienzo. Un cachorro que no completa aún su vacunación y aparece decaído necesita una evaluación rápida, incluso si parece «sólo una gastroenteritis». El diagnóstico puede incluir pruebas específicas, pero su interpretación corresponde al veterinario. Darle remedios caseros o esperar varios días reduce el tiempo disponible para tratarlo."),
        ("Cómo disminuir exposición de otros perros", "Avisá al centro antes de entrar para que organice el ingreso y la atención. Evitá compartir transportadora, platos y espacios con otros perros; el virus es muy contagioso y puede persistir en el ambiente. Si en casa hay más animales, contá sus edades y estado de vacunación. El equipo veterinario indicará cómo limpiar y qué seguimiento necesitan. La prevención depende de un calendario de vacunación apropiado y de decisiones sobre salidas y contacto mientras la protección del cachorro se completa."),
    ],
    "vomitos-y-diarrea": [
        ("Mirar la frecuencia y al animal completo", "Un episodio aislado no se interpreta igual que vómitos repetidos o una diarrea que continúa. Anotá hora, cantidad aproximada, color, presencia de sangre y si bebe, orina y mantiene la actividad habitual. Revisá si pudo tragar un juguete, acceder a basura o ingerir alguna sustancia. Una foto o una muestra, si el veterinario la solicita, puede ayudar. En cachorros, animales mayores o con enfermedades previas conviene consultar antes, porque tienen menos margen para perder líquidos."),
        ("Decisiones que no conviene tomar sin guía", "No retires el agua por tu cuenta ni fuerces comida o bebida si vomita repetidamente; llamá para recibir instrucciones adecuadas al caso. Tampoco uses antidiarreicos o analgésicos humanos. Un abdomen distendido, dolor intenso, sangre, decaimiento marcado o incapacidad para retener agua justifican atención rápida. En la consulta pueden valorar hidratación, temperatura y dolor, y decidir si hace falta un estudio. La causa puede estar en el aparato digestivo o en otro problema del organismo."),
    ],
    "pulgas-y-garrapatas": [
        ("La prevención se elige para cada animal", "Antes de comprar un producto, confirmá especie, peso, edad, enfermedades y otros medicamentos que usa. Algunas formulaciones para perros contienen sustancias peligrosas para gatos; tampoco conviene trasladar una dosis de un animal a otro. Preguntá cada cuánto aplicarlo y qué hacer si se olvida una dosis. Si conviven varias mascotas, el plan debe contemplarlas a todas y también las camas y zonas donde pasan tiempo. Un baño aislado puede no resolver el ciclo de las pulgas."),
        ("Después de encontrar un parásito", "Revisá piel y pelo con buena luz, especialmente orejas, cuello, axilas y entre los dedos después de paseos en vegetación. Si ves una garrapata, pedí indicaciones para retirarla con una herramienta apropiada, sin aplastarla ni aplicar aceite o calor. Anotá cuándo la encontraste y observá si aparecen fiebre, decaimiento, falta de apetito o dolor. Una infestación importante, heridas por rascado o cambios de salud requieren consulta. La elección del control depende del riesgo de ese animal y de su entorno."),
    ],
})

# The prevention and symptom guides need a little more room than a breed profile.
EXPANSIONS["vacunas-perros-gatos"].append(("Si se atrasó una dosis", "No des por perdido todo el esquema ni repitas vacunas por intuición. Pedí un turno con la libreta y contá cuándo fue la última dosis conocida; la respuesta depende de la edad, la vacuna y el riesgo de exposición. Un animal que viaja, vive con otros o empieza a salir puede necesitar una conversación distinta de uno que permanece en casa. Mientras se resuelve, preguntá qué contactos o ambientes conviene evitar. La recomendación tiene que quedar escrita y ser comprensible para quien cuida al animal."))
EXPANSIONS["salud-dental-perros-gatos"].append(("Qué esperar de una evaluación dental", "El veterinario puede revisar encías, piezas fracturadas, movilidad y dolor, y decidir si necesita una limpieza o estudios. La AVMA advierte que limpiar el sarro visible sin anestesia no permite examinar ni tratar debajo de la encía, donde puede haber enfermedad. Si se propone un procedimiento, preguntá por evaluación previa, cuidados posteriores y cómo mantener la boca en casa. Si tu animal no se deja tocar, no fuerces una inspección dolorosa: describí lo que observaste al comer y al jugar."))
EXPANSIONS["peso-saludable-mascotas"].append(("Seguir una tendencia sin obsesionarse con el número", "Acordá con el veterinario cuándo volver a pesar al animal y qué cambios buscar además de la balanza: energía, facilidad para moverse y masa muscular. Usá la misma balanza cuando sea posible y anotá cambios de alimento, apetito o actividad. Si un gato deja de comer al reducir la ración, o un perro pierde peso sin buscarlo, consultá pronto. Un plan útil no persigue un número aislado: busca que el animal se mueva cómodo y reciba todos los nutrientes que necesita."))
EXPANSIONS["golpe-de-calor-mascotas"].append(("Después del episodio", "Contá a la guardia cuánto tiempo estuvo al calor, qué signos viste, si vomitó o se desplomó y qué hiciste para enfriarlo. Esa secuencia ayuda a decidir la atención, incluso si la mascota parece mejor durante el traslado. No vuelvas a ejercitarla ese día ni supongas que el problema terminó porque dejó de jadear. Más adelante, revisá qué situación lo provocó: horario de paseo, falta de sombra, encierro o esfuerzo. Prevenir el siguiente episodio requiere cambiar esas condiciones, no sólo llevar más agua."))
EXPANSIONS["parvovirus-en-perros"].append(("Preguntas útiles durante el tratamiento", "Preguntá cómo se manejarán hidratación, vómitos y alimentación, qué señales indicarían mejoría y cuándo se programará el control. La atención puede requerir internación u otros cuidados según la gravedad; no existe una solución casera equivalente. Si hay otros perros en la casa, consultá por aislamiento, limpieza y vacunación de cada uno. Cuando el cachorro se recupere, seguí las indicaciones sobre el regreso a espacios compartidos. La información general ayuda a prepararte, pero el plan depende del examen y la evolución real."))
EXPANSIONS["vomitos-y-diarrea"].append(("Preparar una consulta que ahorre tiempo", "Llevá una lista de medicaciones y suplementos, marca y cantidad de alimento, fecha de la última desparasitación y cualquier cambio reciente de dieta. Si hay varios animales, contá si alguno más está enfermo. Un video puede ayudar a distinguir vómito de regurgitación, pero no retrases el traslado para grabarlo. Preguntá qué signos obligarían a volver de inmediato y cuándo reanudar la comida habitual. La respuesta no es igual para un adulto estable, un cachorro o un gato con enfermedad previa."))
EXPANSIONS["pulgas-y-garrapatas"].append(("Cuándo revisar el ambiente", "Si aparecen pulgas una y otra vez, no alcanza con mirar sólo al animal que se rasca. Revisá camas, mantas y los lugares donde descansan todas las mascotas; consultá cómo limpiar el entorno sin exponerlas a productos inadecuados. Anotá fecha y nombre del último antiparasitario antes de volver a aplicar otro: combinar tratamientos sin guía aumenta el riesgo de reacciones. Si un gato recibió por error una pipeta para perros y presenta temblores o convulsiones, es una urgencia veterinaria."))

CTA = {
    "caniche": ("¿El cepillado empezó a molestarlo?", "Contanos qué cambió en su piel, pelo o rutina."),
    "corgi": ("¿Notás distinta su forma de caminar?", "Describinos cuándo apareció y qué actividades evita."),
    "perro-salchicha": ("¿Te preocupa su espalda?", "Si hay debilidad o dolor intenso, buscá atención urgente."),
    "golden-retriever": ("¿Tu golden cambió el ritmo?", "Podemos conversar sobre movimiento, piel o controles."),
    "bulldog-frances": ("¿Te inquieta cómo respira?", "En una urgencia respiratoria, acudí a una guardia sin esperar mensajes."),
    "dalmata": ("¿Cambió su manera de orinar?", "Contanos qué observaste; si no puede orinar, necesita atención inmediata."),
    "husky-siberiano": ("¿El calor está cambiando sus paseos?", "Hablemos de horarios, actividad y señales de alarma."),
    "shiba-inu": ("¿Hay algo nuevo en su conducta?", "Describí el contexto y desde cuándo lo notás."),
    "beagle": ("¿Buscás una rutina para tu beagle?", "Podemos revisar paseos, premios y hábitos diarios."),
    "pitbull": ("¿Querés conocer mejor al perro que cuidás?", "Su historia importa más que cualquier etiqueta."),
    "perro-mestizo": ("¿Acaba de llegar a tu casa?", "Contanos qué sabés de él y organizamos los primeros controles."),
    "chihuahua": ("¿Un cambio pequeño te llamó la atención?", "En un cuerpo chico también vale la pena mirarlo a tiempo."),
    "gato-primer-ano": ("¿Llegó un gatito a casa?", "Podemos ordenar sus primeros controles y tus preguntas."),
    "gato-de-interior": ("¿Querés adaptar su espacio?", "Contanos cómo vive y qué actividades disfruta."),
    "gato-agua-y-arenero": ("¿Cambió el uso del arenero?", "Si hace fuerza sin orinar, necesitás atención veterinaria inmediata."),
    "gato-mayor": ("¿Tu gato ya no hace algo que hacía?", "Ese detalle puede ayudar a orientar una revisión."),
    "loro": ("¿Sabés exactamente qué especie es?", "Ese dato nos ayuda a orientar mejor la consulta."),
    "ninfa": ("¿Notaste un cambio en tu ninfa?", "Anotá su apetito, postura y actividad antes de escribirnos."),
    "periquito": ("¿Tu periquito está más quieto?", "Los cambios de rutina en un ave merecen atención temprana."),
    "canario": ("¿Cambió su canto o su energía?", "Contanos también cómo come y se mueve."),
    "conejo": ("¿Tu conejo dejó de comer?", "Consultá pronto: esperar puede complicar un problema digestivo."),
    "cobayo": ("¿Tu cobayo come menos?", "Podemos ayudarte a organizar una consulta sin demoras."),
    "hamster": ("¿Cambió su actividad nocturna?", "Describinos su ambiente y los cambios que viste."),
    "tortuga": ("¿Tenés dudas sobre su hábitat?", "La especie y una foto del recinto son un buen punto de partida."),
    "vacunas-perros-gatos": ("¿Tenés una libreta incompleta?", "Revisemos juntos qué datos hay y qué falta decidir."),
    "salud-dental-perros-gatos": ("¿Le molesta comer o tiene mal aliento?", "Una revisión de la boca puede aclarar qué necesita."),
    "peso-saludable-mascotas": ("¿Cambió de peso sin buscarlo?", "Llevá su alimentación y evolución a una evaluación."),
    "golpe-de-calor-mascotas": ("¿Sospechás un golpe de calor?", "Es una urgencia: acudí a atención veterinaria inmediata."),
    "parvovirus-en-perros": ("¿Tu cachorro está decaído y vomita?", "Avisá al centro antes de llegar y buscá atención rápida."),
    "vomitos-y-diarrea": ("¿Los episodios se repiten?", "Contanos cuándo comenzaron; si está decaído, consultá pronto."),
    "pulgas-y-garrapatas": ("¿Encontraste un parásito?", "Podemos revisar qué prevención corresponde a tu animal."),
}
