"""Additional, source-grounded context for the original Mimo guides."""

ENRICHMENTS = {}


def add(slug, heading, text, faqs, source=None):
    ENRICHMENTS[slug] = {"section": (heading, text), "faqs": faqs, "source": source}


add("caniche", "De perro de agua a compañero de todos los tamaños",
    "El caniche no nació para lucir un corte de pelo: sus antepasados se usaban para recuperar aves en el agua. Su historia se relaciona con Europa continental, especialmente Alemania y Francia; no hay que reducirla a un único país. El nombre francés «caniche» se vincula con el pato, mientras que «poodle» recuerda su trabajo en el agua. El tamaño estándar y las variedades más pequeñas comparten curiosidad y capacidad de aprender, aunque sus necesidades concretas dependen de la edad y del individuo. Esa historia ayuda a entender por qué un juego de búsqueda, un paseo con olores y un rato de aprendizaje pueden interesarle tanto como una vuelta larga. El corte del pelo debe servir a su comodidad y al cuidado de la piel, no a una imagen ideal de la raza.",
    [("¿El caniche es originalmente francés?", "Se lo asocia mucho con Francia, pero su desarrollo histórico incluye otras regiones europeas. Lo más claro es su antigua función como perro de agua."),
     ("¿Un caniche toy se cuida igual que uno grande?", "Comparten rasgos de la raza, pero la porción de comida, el manejo físico y la intensidad de actividad deben adaptarse a su tamaño, edad y salud.")],
    ("AKC · historia del caniche", "https://www.akc.org/expert-advice/dog-breeds/poodle-history/"))

add("corgi", "El pequeño pastor que viene de Gales",
    "El Pembroke Welsh Corgi se desarrolló como perro de granja en Gales y ayudaba a mover el ganado. Sus patas cortas no significan que haya sido criado para una vida sedentaria: podía acompañar tareas, estar atento al entorno y responder a lo que pasaba alrededor. «Pembroke» señala una región galesa; además existe el Cardigan Welsh Corgi, que es otra raza. Saber de dónde viene evita confundir su silueta con fragilidad o con poca necesidad de movimiento. En casa le pueden venir bien paseos, consignas sencillas y juegos que le permitan usar la cabeza. Conviene combinar esa actividad con pausas, controlar los premios y consultar si cambia su manera de subir, bajar o levantarse.",
    [("¿Todos los corgis son la misma raza?", "No. Pembroke y Cardigan son razas distintas; esta guía se centra en el Pembroke, aunque muchos cuidados cotidianos se parecen."),
     ("¿Por qué un corgi intenta perseguir movimientos?", "Su pasado de trabajo con ganado puede ayudar a entender esa inclinación. Se puede ofrecer juego y aprendizaje sin dejar que persiga bicicletas, autos o personas.")],
    ("AKC · historia del Pembroke Welsh Corgi", "https://www.akc.org/expert-advice/dog-breeds/pembroke-welsh-corgi-history/"))

add("perro-salchicha", "Por qué se llama dachshund",
    "Dachshund significa «perro de tejón» en alemán. La raza se desarrolló para seguir presas en madrigueras: de ahí su cuerpo largo, las patas cortas y una personalidad que suele explorar con decisión. También se lo conoce como teckel o, cariñosamente, perro salchicha. Su historia explica por qué necesita olfatear y moverse, aun cuando cuidemos su columna. El objetivo no es dejarlo inmóvil: una rutina estable, peso adecuado y juego a nivel del suelo lo ayudan a conservar fuerza. Observá cómo camina y cómo se incorpora. Si aparece dolor, arrastra una pata o pierde control de la orina o las heces, se trata de una consulta urgente; no esperes a que el episodio termine solo.",
    [("¿El nombre «salchicha» es el nombre de la raza?", "Es un apodo por su silueta. Dachshund o teckel son los nombres usados para la raza."),
     ("¿Una rampa elimina el riesgo de lesión de espalda?", "Puede ayudar a evitar algunos saltos, pero no reemplaza el control del peso, la actividad apropiada ni una consulta ante dolor o debilidad.")],
    ("AKC · historia del dachshund", "https://www.akc.org/expert-advice/dog-breeds/dachshund-history-badger-dog-breed/"))

add("golden-retriever", "Un perro de cobro nacido en Escocia",
    "El golden retriever fue desarrollado en las Tierras Altas de Escocia para recuperar aves en terrenos y aguas difíciles. «Retriever» alude justamente a traer de vuelta lo cobrado; «golden», a su manto dorado. Su origen de trabajo ayuda a explicar por qué a muchos les gusta llevar objetos, explorar y colaborar con las personas. No hace falta convertir cada paseo en entrenamiento: alternar movimiento, juegos de búsqueda, ratos de agua cuando sea seguro y descanso resulta más sostenible. A medida que crece o envejece, la intensidad se ajusta. Si muestra rigidez, deja de subir al auto o tarda en recuperarse después de jugar, esa información merece una revisión, sin asumir que sea simplemente «la edad».",
    [("¿Todos los golden disfrutan nadar?", "Muchos muestran interés por el agua, pero cada perro es distinto. Nunca hay que forzarlo; elegí espacios seguros y supervisá la actividad."),
     ("¿Por qué quiere llevar objetos?", "La raza se seleccionó para recuperar presas. Ofrecer juguetes seguros y enseñar a soltar puede canalizar ese interés sin peleas por los objetos.")],
    ("AKC · historia del golden retriever", "https://www.akc.org/expert-advice/dog-breeds/golden-retriever-history/"))

add("bulldog-frances", "De Inglaterra a Francia, con una pregunta de bienestar",
    "El bulldog francés desciende de pequeños bulldogs llevados desde Inglaterra a Francia, donde se desarrolló como perro de compañía. Su nombre cuenta ese recorrido; su cara corta, en cambio, exige mirar la salud presente. Una respiración muy ruidosa, el cansancio desproporcionado, las arcadas o la dificultad para recuperarse después de un paseo no son rasgos simpáticos que haya que aceptar. La conformación braquicéfala puede limitar el paso del aire y aumentar el riesgo con el calor. En la consulta conviene contar qué ocurre al dormir, jugar y salir, además de llevar videos breves si un episodio no aparece en el consultorio. El veterinario puede indicar si necesita evaluación respiratoria específica y cómo adaptar su rutina.",
    [("¿El bulldog francés viene de Francia?", "La raza se consolidó en Francia a partir de pequeños bulldogs procedentes de Inglaterra."),
     ("¿Roncar fuerte es parte normal de la raza?", "No conviene normalizarlo. El ruido, sobre todo si se acompaña de esfuerzo o fatiga, merece una evaluación clínica.")],
    ("AKC · historia del bulldog francés", "https://www.akc.org/expert-advice/dog-breeds/breed-history-french-bulldog/"))

add("dalmata", "Las manchas, el nombre y una historia de movimiento",
    "El nombre dálmata se vincula con Dalmacia, en la costa del Adriático, aunque los detalles de sus orígenes más antiguos no están completamente resueltos. Históricamente acompañó carruajes y caballos, un papel que ayuda a entender su resistencia y su atención al movimiento. Hoy esa energía necesita una salida segura: paseos regulares, juegos compartidos y descanso. Hay otro dato importante que no se ve en las manchas: en la raza se presta especial atención a la salud urinaria. Si hace fuerza para orinar, sale poca cantidad, hay sangre o parece dolorido, pedí atención veterinaria; la dificultad para orinar puede ser urgente. La dieta y cualquier control adicional deben ajustarse a su historia clínica, no a una receta general para todos los dálmatas.",
    [("¿Las manchas aparecen al nacer?", "Los cachorros suelen nacer con el pelo mayormente blanco; las manchas visibles se desarrollan después. Consultá cualquier cambio de piel que parezca irritación."),
     ("¿La sordera afecta a todos los dálmatas?", "No. Es una condición a considerar en la raza, pero sólo una evaluación auditiva permite saber cómo oye un perro concreto.")],
    ("AKC · dálmata", "https://www.akc.org/dog-breeds/dalmatian/"))

add("husky-siberiano", "Un compañero de trabajo de Siberia",
    "El husky siberiano fue criado por el pueblo chukchi del noreste de Asia para tirar trineos y convivir cerca de las familias. No es sólo un perro de pelo abundante y ojos llamativos: su pasado explica tanto la disposición a moverse como la curiosidad por recorrer. En un clima cálido como el de Buenos Aires, la actividad requiere horarios frescos, agua y pausas; no hace falta exigirle correr para demostrar que hace suficiente ejercicio. Juegos de olfato y paseos tranquilos también suman. Es importante revisar cierres, correa y chapita o identificación, porque un perro interesado en explorar puede alejarse rápido. El cepillado ayuda a manejar el pelo suelto sin quitarle a la ligera la protección de su manto.",
    [("¿Husky significa lobo?", "No. Es una raza de perro doméstico con una historia vinculada al trabajo de trineo; su aspecto no lo convierte en un lobo."),
     ("¿Se le puede rapar para que tenga menos calor?", "En general no se recomienda cortar el manto al ras por cuenta propia. Consultá cómo manejar cepillado, sombra y actividad según su situación.")],
    ("AKC · historia del husky siberiano", "https://www.akc.org/expert-advice/dog-breeds/siberian-husky-history/"))

add("shiba-inu", "Una raza japonesa con un nombre que admite matices",
    "El shiba inu es una raza japonesa antigua vinculada a la caza en terrenos con vegetación. «Inu» significa perro; el origen preciso de «shiba» se discute y suele asociarse al matorral o a su color, por lo que conviene no presentar una traducción única como certeza. Su historia ayuda a comprender la importancia de explorar y de tomar distancia cuando algo lo incomoda. Eso no significa que no pueda aprender: suele resultar más útil una enseñanza breve, predecible y con recompensas que forzar el contacto. Una correa segura y un entorno controlado importan incluso si responde bien en casa. Si empieza a evitar caricias, se esconde o reacciona al tocarlo, considerá también dolor o malestar antes de atribuirlo a su «carácter».",
    [("¿Es cierto que los shiba son imposibles de educar?", "No. Pueden aprender, pero la constancia, la motivación y el respeto de sus señales suelen funcionar mejor que la presión."),
     ("¿Por qué no conviene soltarlo en cualquier lugar?", "La curiosidad y el interés por perseguir movimiento pueden superar una llamada aprendida. Usá espacios cercados y una identificación actualizada.")],
    ("AKC · historia del shiba inu", "https://www.akc.org/expert-advice/dog-breeds/shiba-inu-breed-history/"))

add("beagle", "Un sabueso que sigue historias con la nariz",
    "El beagle se desarrolló en Inglaterra como perro de rastro que trabajaba en grupo. Su nombre tiene explicaciones históricas distintas y no hay una etimología única confirmada. Más útil para la vida diaria es entender para qué se seleccionó: seguir olores durante tiempo, incluso cuando su persona preferiría volver. Un paseo con tramos para olfatear suele ofrecerle más que caminar apurado en línea recta. En casa podés esconder parte de su ración en un juguete o en una búsqueda sencilla, contando esa comida dentro del total del día. Afuera, la correa y una identificación visible previenen extravíos. Si el interés por la comida cambia de golpe o gana peso, llevalo a un control antes de reducir la ración sin criterio.",
    [("¿Por qué no me escucha cuando huele algo?", "Seguir rastros forma parte de lo que la raza fue seleccionada para hacer. Practicá llamados en contextos fáciles y mantené una correa segura donde haya distracciones."),
     ("¿El beagle necesita vivir con otros perros?", "Su historia de trabajo en grupo no obliga a convivir con otro. Lo importante es evaluar su sociabilidad individual y ofrecerle compañía, actividad y descanso.")],
    ("AKC · beagle", "https://www.akc.org/dog-breeds/beagle/"))

add("pitbull", "Qué dice, y qué no dice, la palabra «pitbull»",
    "«Pitbull» se usa para nombrar perros de aspecto parecido, no siempre una única raza identificable. Puede referirse al American Pit Bull Terrier u otras razas y mezclas. Por eso, una etiqueta visual no permite predecir cómo se comporta un individuo, qué experiencias tuvo ni qué apoyo necesita. La historia de cada perro, su salud, el ambiente y las interacciones que aprende a manejar importan más para organizar la convivencia. Observá si se tensa, busca distancia, deja de aceptar comida o se recupera rápido de una situación difícil. Un plan de paseos con arnés adecuado, encuentros graduales y enseñanza basada en recompensas ayuda a tomar decisiones concretas. Si hay riesgo de mordida o cambios bruscos de conducta, pedí una evaluación profesional sin esperar a que se repita el episodio.",
    [("¿Pitbull y American Bully son lo mismo?", "No. American Bully tiene un estándar propio; «pitbull» se usa de forma amplia e imprecisa. El cuidado y la evaluación deben centrarse en cada perro."),
     ("¿Se puede saber si es peligroso por la cabeza?", "La forma de la cabeza no permite anticipar de manera fiable la conducta de un perro. Se necesitan observación, contexto e historia individual.")],
    ("AKC · por qué las etiquetas de raza pueden fallar", "https://www.akc.org/expert-advice/news/breed-bans-affect/"))

add("perro-mestizo", "Una historia propia, aunque no sepamos su mezcla",
    "Un perro mestizo no necesita un porcentaje de razas para recibir buenos cuidados. Si llegó de un refugio, de la calle o de otra familia, la información previa puede ser incompleta. Empezá por lo observable: edad aproximada, tamaño, peso, estado de piel y dientes, hábitos de comida, descanso y reacción ante el contacto. Una primera consulta ayuda a organizar identificación, vacunas, antiparasitarios y cualquier problema pendiente. Durante la adaptación, mantené horarios bastante estables y permitile un sitio donde retirarse. Tomar fotos o notas semanales puede mostrar cambios de peso y comportamiento que no se ven de un día a otro. Si algo preocupa, describí el hecho concreto —por ejemplo, «cojea al levantarse»— en lugar de atribuirlo a la mezcla que imaginás.",
    [("¿Necesito un test de ADN para saber qué cuidados darle?", "No. Puede ser una curiosidad, pero el plan de salud se construye con examen clínico, edad, tamaño, hábitos y antecedentes conocidos."),
     ("¿Cuánto tarda en adaptarse a una casa nueva?", "No hay un plazo fijo. Dale una rutina predecible y observá si come, descansa y se siente cada vez más cómodo; consultá si el miedo o el malestar persisten.")])

add("chihuahua", "Un nombre mexicano para un perro pequeño con necesidades completas",
    "La raza toma su nombre del estado de Chihuahua, en México. Su ascendencia antigua tiene aspectos discutidos, así que conviene distinguir el origen del nombre de una genealogía completamente comprobada. El tamaño puede hacer que parezca cómodo llevarlo siempre en brazos, pero también necesita caminar, olfatear y elegir cuándo acercarse. Para evitar sustos, enseñá a chicos y adultos a invitarlo al contacto y a dejarlo descansar sin perseguirlo. En los controles prestá atención a la boca, la condición corporal y la forma en que se mueve. Si tiembla, no supongas automáticamente que es «cosa de chihuahuas»: puede tener frío, miedo, dolor u otra causa que merece observarse en contexto.",
    [("¿Chihuahua y «chihuahueño» son nombres distintos?", "Ambos nombres se usan para referirse a la raza; «chihuahua» proviene del estado mexicano."),
     ("¿Hay que protegerlo cargándolo todo el tiempo?", "No. Se beneficia de movimiento y experiencias positivas a su escala, con supervisión en lugares donde podrían pisarlo o lastimarlo.")],
    ("AKC · chihuahua", "https://www.akc.org/dog-breeds/chihuahua/"))

add("gato-primer-ano", "Una casa segura antes de explorar toda la casa",
    "Durante los primeros días, prepará una habitación tranquila con comida, agua, arenero y un lugar para esconderse, separados en lo posible. Abrirle toda la vivienda de inmediato puede abrumarlo y dificulta saber si está comiendo o usando el arenero. Revisá ventanas, balcones, cables, plantas y objetos pequeños que pueda tragar. Si convive con otros animales, el intercambio de olores y las presentaciones graduales suelen ser más amables que ponerlos frente a frente. Registrá peso, apetito y heces; los gatitos pueden deshidratarse o empeorar rápido cuando dejan de comer. La primera consulta es un buen momento para hablar de vacunas, desparasitación, identificación y edad apropiada para la castración según su caso.",
    [("¿Puede dormir escondido los primeros días?", "Sí, buscar refugio puede ser parte de la adaptación. Aun así, verificá que coma, beba y use el arenero; consultá si no lo hace."),
     ("¿Qué hago si hay un perro en casa?", "Empezá con separación física, intercambio de olores y encuentros breves supervisados. Asegurá siempre una vía de escape elevada para el gato.")])

add("gato-de-interior", "Diseñar opciones, no llenar la casa de objetos",
    "Para un gato de interior, la calidad del espacio importa más que acumular juguetes. Conviene ofrecer distintas alturas, escondites, rascadores firmes y lugares de descanso lejos del paso. Si hay varios gatos, distribuir comida, agua y areneros en sitios separados reduce la competencia silenciosa. Observá dónde elige dormir, desde qué lugar mira la ventana y qué recorrido evita; esa información revela si el ambiente le resulta cómodo. Una sesión breve de juego de persecución con un juguete que pueda «capturar», seguida de una pequeña porción de comida, puede ser más satisfactoria que dejar un juguete inmóvil todo el día. Rotar objetos de a poco mantiene el interés sin cambiarle constantemente su territorio.",
    [("¿Un gato de interior se aburre necesariamente?", "No. Puede vivir bien adentro si tiene oportunidades de explorar, jugar, descansar y controlar el contacto. Mirá su conducta, no sólo los metros cuadrados."),
     ("¿Cuántos rascadores necesita?", "Depende del espacio y de los gatos. Ofrecé al menos opciones firmes en lugares que ya usa, con superficies y orientaciones distintas.")])

add("gato-agua-y-arenero", "Un registro sencillo puede adelantar una consulta",
    "Tomá nota de cuántas veces usa el arenero, si hace montículos de orina de tamaño parecido y si cambió la cantidad que bebe. No se trata de medir todo cada día, sino de conocer su patrón. Si hay varios gatos, a veces ayuda observarlos por separado durante un rato. Ofrecé agua fresca en más de un sitio, lejos del arenero, y probá recipientes que no rocen los bigotes si parece evitar uno. Limpiá el arenero con regularidad y no lo escondas en una zona ruidosa o de paso obligado. Un gato que entra muchas veces y produce poca orina, se queja o está decaído necesita atención rápida; si no puede orinar, es una urgencia.",
    [("¿Cuánta agua debería tomar?", "La cantidad varía con su alimento, ambiente y salud. Si notás un aumento o descenso claro de su patrón habitual, consultá."),
     ("¿Cambio toda la arena de golpe?", "Si querés probar otra textura, una transición gradual y la posibilidad de elegir entre dos bandejas pueden evitar rechazo.")])

add("gato-mayor", "El envejecimiento no explica todo",
    "Un gato mayor puede seguir jugando y buscando contacto, pero tal vez necesita que el entorno se adapte. Si deja de subir a su lugar favorito, no llega al arenero a tiempo o se asea menos, podría haber dolor articular u otra condición tratable. Una bandeja de entrada baja, escalones firmes y lugares de descanso accesibles ayudan mientras se investiga la causa. Pesalo periódicamente con una balanza confiable y anotá cambios de sed, apetito y vocalización. La pérdida de peso puede pasar inadvertida bajo el pelo; el aumento de agua tampoco debería atribuirse sólo a la edad. Llevar esas observaciones a consulta permite decidir qué examen o análisis corresponde, sin suponer un diagnóstico desde casa.",
    [("¿Cada cuánto debería controlarse un gato mayor?", "La frecuencia se decide según edad y salud. Si aparecen cambios de peso, sed, movilidad o conducta, adelantá la consulta en vez de esperar al control habitual."),
     ("¿Debo cambiarle la comida por ser mayor?", "No por la etiqueta de edad solamente. La elección depende de su condición corporal, enfermedades y capacidad para comer; consultalo con su veterinario.")])

add("loro", "La especie cambia la respuesta",
    "«Loro» reúne aves de tamaños, dietas y longevidades muy diferentes. Antes de aplicar una recomendación, identificá la especie: no es igual organizar la alimentación y el espacio de un amazona que los de un ave más pequeña. Anotá qué come realmente durante una semana, incluyendo semillas, frutas, premios y comida ofrecida por otras personas. Los cambios de dieta deben ser graduales y acompañados; no retires de golpe el alimento conocido para obligarlo a aceptar otro. En la casa, revisá ventanas, ventiladores, recipientes con agua y vapores de cocina antes de permitir vuelo. Un ave quieta, embolada, que come menos o cambia sus heces necesita una consulta pronta con un profesional que atienda aves, porque puede ocultar enfermedad.",
    [("¿Sirve una mezcla de semillas para todos los loros?", "No. Las necesidades dependen de la especie y una dieta de semillas como único alimento puede ser insuficiente. Pedí una evaluación individual."),
     ("¿Puedo darle comida de mi plato?", "No conviene improvisar. Algunos alimentos y condimentos son peligrosos; consultá qué ingredientes y cantidades son adecuados para su especie.")])

add("ninfa", "Una rutina que se pueda observar",
    "La ninfa, también llamada cacatúa carolina, puede parecer animada incluso cuando un problema recién empieza. Elegí un momento diario para mirar apetito, peso si podés medirlo sin estrés, heces, plumaje y modo de apoyarse en la percha. Esa normalidad propia es más valiosa que una lista general de síntomas. Ofrecé espacio para extender las alas y varias perchas de grosor y textura apropiados, ubicadas de forma que no ensucie la comida o el agua. Evitá corrientes de aire, humo y vapores de cocina. Si vive con otra ave, la convivencia debe observarse: compartir jaula no garantiza que ambas puedan comer y descansar sin ser desplazadas.",
    [("¿Es normal que esté callada un día?", "El canto varía, pero el silencio junto con menos apetito, plumas erizadas o menor actividad merece consulta veterinaria."),
     ("¿Puede bañarse?", "Muchas disfrutan una oferta suave de agua, pero no la fuerces. Asegurá un ambiente templado y dejá que se seque sin corrientes de aire.")])

add("periquito", "Pequeño tamaño, cambios que importan mucho",
    "En un periquito, la pérdida de peso o un día con menos comida puede tener más impacto del que parece. Conviene reconocer cómo son sus heces, cuánto tiempo pasa activo y qué alimento elige de verdad; una cáscara vacía en el comedero puede hacer pensar que comió más de lo que comió. Un espacio horizontal suficiente para desplazarse, perchas variadas y tiempo seguro fuera de la jaula permiten ejercitarse. Si se ofrecen nuevos alimentos, mantené disponible lo que ya conoce mientras aprende a probarlos. Respirar con esfuerzo, quedarse en el piso de la jaula, dejar de comer o permanecer muy quieto son motivos para buscar atención veterinaria con experiencia en aves sin esperar varios días.",
    [("¿Necesita un espejo para no sentirse solo?", "Un espejo no sustituye interacción, espacio ni enriquecimiento. Observá cómo responde; si lo defiende o deja de participar en otras actividades, consultá."),
     ("¿Cómo sé si comió si hay semillas en el comedero?", "Revisá si quedan semillas enteras o sólo cáscaras, y controlá su conducta y peso. Ante dudas o pérdida de apetito, consultá pronto.")])

add("canario", "Escuchar su canto, mirar el resto",
    "El canto puede variar por edad, muda, luz ambiental y contexto. Por eso, un canario que canta menos no tiene necesariamente una enfermedad, pero tampoco conviene ignorar otros cambios. Mirá si se alimenta, cómo se posa, si respira con esfuerzo y si las heces mantienen su aspecto habitual. Su jaula debe permitir desplazamientos entre perchas, lejos de humo, aerosoles y vapores de cocina. Un fotoperíodo estable, con noche de descanso, ayuda a ordenar su rutina. Para limpiarla, trasladalo de forma segura y usá productos que puedan enjuagarse bien; los olores fuertes pueden irritar a las aves. Si se mantiene embolado, en el piso o sin comer, pedí atención de un veterinario de aves.",
    [("¿Si no canta significa que está enfermo?", "No siempre. Mirá apetito, actividad, respiración y heces, y consultá si aparecen otros cambios o el silencio persiste."),
     ("¿Puede vivir en una cocina?", "No es un buen lugar: humo, aerosoles, vapores y cambios de temperatura pueden ser peligrosos para las aves.")])

add("conejo", "El cuerpo del conejo necesita una rutina constante",
    "El heno disponible todo el tiempo no es un accesorio: aporta fibra y favorece la masticación. Si un conejo come menos heno, deja de producir heces o permanece quieto y encorvado, hay que buscar atención veterinaria pronta. Prepará una zona donde pueda correr, esconderse y apoyarse sobre un piso que no lastime sus patas. Los cambios de alimento se hacen gradualmente, observando apetito y heces. Como especie social, muchos conejos se benefician de la compañía de otro conejo compatible, pero una presentación debe planificarse y supervisarse. Al alzarlo, si es imprescindible, sostené bien pecho y parte trasera; un salto de miedo puede lesionarlo. Un veterinario con experiencia en conejos puede ayudarte a ajustar comida, ambiente y prevención.",
    [("¿Las zanahorias pueden ser su comida principal?", "No. El heno debe ser la base; los vegetales y otros alimentos se eligen en cantidades apropiadas con asesoramiento."),
     ("¿Por qué deja de hacer heces?", "Puede ser señal de un problema serio. No intentes resolverlo sólo con un cambio de comida; buscá atención veterinaria cuanto antes.")])

add("cobayo", "La vitamina C también depende de cómo guardás su comida",
    "Los cobayos no producen suficiente vitamina C por sí mismos y necesitan recibirla en la dieta. Un alimento formulado para cobayos, heno constante y vegetales adecuados son el punto de partida, pero la vitamina C del alimento puede disminuir con el almacenamiento prolongado. Por eso importa revisar fecha, cierre del envase y cantidad realmente consumida. No agregues suplementos al agua por cuenta propia: pueden alterar el sabor y hacer que beba menos, además de no asegurar la dosis. Ofrecé escondites y espacio para moverse sobre un piso firme y limpio; pesarlo con regularidad puede revelar un problema antes de que su pelaje lo muestre. Si deja de comer o de producir heces, consultá rápido.",
    [("¿Alcanza con poner vitamina C en el agua?", "No suele ser una forma confiable de asegurar la cantidad necesaria y puede reducir el consumo de agua. Consultá una dieta y suplemento apropiados."),
     ("¿Por qué conviene pesarlo?", "La pérdida gradual puede ocultarse bajo el pelo. Un registro periódico ayuda a detectar cambios y llevar datos útiles a la consulta.")])

add("hamster", "Dejarlo vivir a su propio horario",
    "Los hámsters suelen estar más activos al atardecer y por la noche. Despertarlo para jugar de día puede asustarlo y dificultar el vínculo. En lugar de eso, observá cuándo sale solo, ofrecé la mano quieta y dejá que se acerque. Un recinto con sustrato profundo para excavar, escondite, rueda de tamaño adecuado y oportunidades de buscar comida permite conductas naturales. Revisá diariamente agua y alimento, pero respetá su zona de descanso durante la limpieza; una limpieza total y muy frecuente elimina sus olores conocidos. Si deja de moverse, respira raro, presenta diarrea o no come cuando suele hacerlo, pedí ayuda veterinaria. Su tamaño pequeño no hace que esos cambios sean menores.",
    [("¿Por qué muerde cuando lo despierto?", "Puede reaccionar por sobresalto o miedo. Esperá a que esté despierto y dejá que el contacto avance a su ritmo."),
     ("¿Una pelota para correr por la casa es buena idea?", "Puede limitar ventilación y control del entorno. Es preferible ofrecer exploración supervisada en un espacio seguro y una rueda adecuada en su recinto.")])

add("tortuga", "Primero identificá la especie; después armá el hábitat",
    "Bajo la palabra «tortuga» hay especies terrestres y acuáticas con necesidades distintas de temperatura, luz, humedad, agua y alimento. Una foto puede orientar, pero para planificar el cuidado necesitás una identificación confiable. Medí la temperatura real de las zonas cálida y fresca con instrumentos, en lugar de suponer que una lámpara encendida es suficiente. La luz UVB y la superficie de asoleo deben elegirse según la especie y el montaje; los vidrios pueden filtrar parte de la radiación útil. Si es acuática, necesita un lugar donde salir completamente del agua y secarse. Lavate las manos después de manipularla o limpiar su ambiente, porque los reptiles pueden portar Salmonella incluso si parecen sanos. Falta de apetito, ojos hinchados o caparazón blando justifican consulta.",
    [("¿Todas las tortugas comen lechuga?", "No. La dieta cambia mucho entre especies; una sola verdura no cubre sus necesidades."),
     ("¿El sol a través de la ventana reemplaza una luz adecuada?", "No necesariamente. El vidrio puede filtrar radiación UVB, y también hay riesgo de sobrecalentamiento. Consultá el montaje apropiado para su especie.")])

add("vacunas-perros-gatos", "Qué hacer si perdiste la libreta o llegó un adulto sin antecedentes",
    "No conocer las dosis anteriores no significa que el animal no pueda empezar un plan. Llevá cualquier comprobante, fotos de la libreta o datos de la protectora, y contá edad estimada, enfermedades, viajes, contacto con otros animales y posibilidad de exposición. El veterinario decidirá qué vacunas centrales y cuáles adicionales corresponden según riesgo y normas locales, además del intervalo entre aplicaciones. Evitá copiar un calendario de internet: no todos los productos tienen las mismas indicaciones ni todos los animales llegan a consulta en la misma situación. Después de vacunar, anotá fecha, producto y próxima visita; preguntá qué molestias leves pueden aparecer y qué signos requieren llamar o volver de inmediato.",
    [("¿Un gato que no sale de casa necesita vacunas?", "Sí puede necesitarlas. El plan se decide según sus riesgos y la recomendación veterinaria, no sólo por si cruza la puerta."),
     ("¿Se puede vacunar a un animal enfermo?", "Antes de aplicar una vacuna se evalúa su estado general. Contá si vomita, tiene fiebre, toma medicación o mostró un cambio reciente.")])

add("salud-dental-perros-gatos", "Dolor dental que no se anuncia con un quejido",
    "Perros y gatos pueden seguir comiendo aunque tengan dolor de boca. A veces mastican de un solo lado, dejan caer comida, prefieren lo blando, se frotan el hocico o evitan que les toquen la cara. El sarro visible no cuenta toda la historia: puede haber enfermedad debajo de la encía. En la consulta, describí cuándo empezó el cambio y si notaste mal olor, sangrado o inflamación. El cepillado con productos aptos para su especie ayuda a prevenir, pero no quita depósitos endurecidos ni reemplaza una evaluación profesional. Si el animal ya muestra dolor, no insistas en cepillar una zona sensible; primero consultá qué tratamiento necesita y luego armá una rutina de mantenimiento posible.",
    [("¿Un snack dental reemplaza el cepillado?", "Puede formar parte de una rutina si es adecuado, pero no sustituye una revisión ni el cuidado recomendado para ese animal."),
     ("¿Por qué necesita revisión si sigue comiendo?", "Muchos animales continúan comiendo pese al dolor. Sangrado, olor intenso o cambios al masticar son motivos para pedir turno.")])

add("peso-saludable-mascotas", "Mirar la condición corporal, no sólo la balanza",
    "Dos animales que pesan lo mismo pueden tener cuerpos muy diferentes. En consulta se puede valorar si se palpan las costillas con facilidad, si hay cintura visible y cómo se distribuye la grasa, junto con masa muscular y edad. Si necesitás ajustar la comida, medí la ración real durante varios días e incluí premios, restos y porciones que ofrecen otras personas. Un cambio brusco sin evaluar enfermedades puede ser contraproducente, especialmente en gatos. Elegí metas pequeñas, una forma de medir el progreso y actividades que el animal disfrute. Si baja de peso sin haber cambiado la alimentación, o pierde músculo aun con apetito, no lo celebres como resultado de una dieta: consultá para buscar la causa.",
    [("¿Puedo bajar la comida a la mitad?", "No conviene hacerlo por cuenta propia. La reducción debe cuidar nutrientes y adaptarse a especie, edad y salud."),
     ("¿Por qué mi mascota sube de peso si come «poco»?", "Los premios, las porciones compartidas y una actividad menor pueden sumar. También puede haber problemas de salud; un registro ayuda a evaluarlo.")])

add("golpe-de-calor-mascotas", "Una sospecha de sobrecalentamiento exige dos acciones",
    "Si un animal jadea de forma intensa, está débil, tambalea, vomita o no responde como siempre después de calor o esfuerzo, trasladalo de inmediato a un lugar fresco y buscá atención veterinaria urgente. Mientras organizás el traslado, mojalo con agua más fría que su cuerpo y ventilalo; no lo envuelvas en toallas mojadas que retengan calor ni lo obligues a beber si está alterado. La mejoría aparente no descarta daño interno, por lo que necesita evaluación. La prevención empieza antes de salir: mirá temperatura, humedad, pavimento y posibilidad real de sombra y agua. Los animales de cara corta, mayores o con enfermedades pueden tolerar peor el calor, pero cualquiera puede sufrirlo en un auto o ambiente cerrado.",
    [("¿El agua fría puede ser perjudicial?", "La prioridad es empezar a enfriar rápido. En perros, usá agua más fría que el cuerpo; una guardia puede orientar el método más seguro según el estado del animal."),
     ("¿Si vuelve a jugar ya está fuera de peligro?", "No necesariamente. Después de un episodio compatible con golpe de calor puede haber complicaciones; debe ser evaluado.")],
    ("BSAVA · primeros cuidados ante un golpe de calor", "https://www.bsava.com/article/summer-pet-care-and-summer-holidays-with-your-pet/"))

add("parvovirus-en-perros", "La consulta empieza antes de entrar al consultorio",
    "El parvovirus es muy contagioso entre perros y puede ser grave, especialmente en cachorros. Si sospechás por vómitos, diarrea, decaimiento o falta de apetito, llamá antes de llegar para que el equipo indique cómo ingresar sin exponer a otros animales. Llevá fechas de vacunas, edad, inicio de síntomas y cualquier contacto con perros enfermos o ambientes compartidos. La diarrea con sangre puede aparecer, pero no es indispensable para pedir ayuda. No ofrezcas medicación humana ni esperes a que se deshidrate. Mientras se confirma la causa, evitá que comparta comederos, patios o paseos con otros perros y consultá cómo limpiar el ambiente. El diagnóstico y el tratamiento requieren evaluación veterinaria; no se resuelven con una receta casera.",
    [("¿Un perro vacunado puede tener signos parecidos?", "Sí, distintos problemas causan vómitos y diarrea. La vacunación reduce riesgos, pero los síntomas siempre merecen evaluación."),
     ("¿Cuándo puede volver a ver otros perros?", "Depende del diagnóstico, la evolución y el riesgo de contagio. Pedí al veterinario una indicación concreta antes de reanudar encuentros.")])

add("vomitos-y-diarrea", "Una lista breve para decidir la urgencia",
    "Cuando llames al veterinario, contá especie, edad, peso aproximado, número de episodios, presencia de sangre, si bebe, si orina y cómo se comporta entre episodios. Una foto puede ayudar a describir lo que viste, sin sustituir el examen. La urgencia aumenta si se trata de un cachorro o gatito, si hay decaimiento, dolor abdominal, abdomen distendido, intentos de vomitar sin resultado o sospecha de tóxico u objeto ingerido. No todos los cuadros requieren el mismo estudio ni la misma alimentación; evitar tratamientos humanos y dietas improvisadas es parte del cuidado. Si te indican observación en casa, pedí criterios claros para volver a llamar y anotá si los episodios continúan o cambian.",
    [("¿Puedo esperar si vomitó una sola vez?", "Depende de su edad, estado general y otros signos. Si hay decaimiento, dolor, sangre o sospecha de tóxico, consultá de inmediato."),
     ("¿Le doy un medicamento de mi botiquín?", "No. Muchos medicamentos humanos son peligrosos para animales y pueden dificultar el diagnóstico. Consultá antes de administrar algo.")])

add("pulgas-y-garrapatas", "El plan incluye al animal y su entorno",
    "Encontrar una pulga o garrapata no significa que baste con quitar la que se ve. Contá al veterinario qué especie y peso tiene tu animal, qué producto recibió, cuándo se aplicó y si convive con otros. Algunos antiparasitarios para perros son tóxicos para gatos; nunca compartas pipetas ni cambies dosis por tu cuenta. Revisá zonas de descanso, mantas y lugares donde pasan tiempo los animales, porque parte del ciclo de las pulgas ocurre fuera del cuerpo. La prevención se elige según exposición, edad, enfermedades y productos disponibles. Si un animal se rasca mucho, presenta lesiones, encías pálidas o decaimiento, necesita una evaluación. Tras retirar una garrapata, observá la piel y consultá si aparecen signos generales.",
    [("¿Debo tratar a todos los animales de la casa?", "Puede ser necesario coordinar un plan para todos, con productos adecuados a cada especie. Pedí indicación veterinaria antes de aplicarlos."),
     ("¿Una casa limpia puede tener pulgas?", "Sí. La limpieza ayuda, pero una infestación puede requerir medidas dirigidas al animal y al ambiente durante varias semanas.")])
