"""New dog profiles for Mimo. Sources are shown on every generated page."""

ARTICLES = []
BOAS = ("Universidad de Cambridge · problemas respiratorios en perros de cara corta", "https://www.vet.cam.ac.uk/boas/about-boas/recognition-diagnosis")
TRAINING = ("AVSAB · educación y bienestar canino", "https://avsab.org/resources/position-statements/")

def add(slug, title, deck, image, intro, sections, faqs, sources, related, cta):
    ARTICLES.append(dict(slug=slug, category="perros", title=title, deck=deck,
                         image=image, intro=intro, sections=sections, faqs=faqs,
                         sources=sources, related=related, cta=cta))

add("bull-terrier", "Bull terrier: una cabeza única y mucha vida por compartir",
    "De dónde viene su nombre, cómo acompañar su juego y qué observar en casa.", "26-bull-terrier.webp",
    "La forma de su cabeza atrae miradas, pero conocer a un bull terrier exige mirar bastante más. Necesita actividad, límites claros y oportunidades de descansar junto a su gente, con una rutina que tenga sentido para ese perro.",
    [
      ("De dónde salen el nombre y la raza", "En la Inglaterra del siglo XIX se cruzaron perros tipo bulldog con terriers; de esa combinación quedó el nombre bull terrier. Más adelante se lo seleccionó como una raza distinta, con la silueta y el perfil de cabeza que hoy lo identifican. Conocer ese origen explica rasgos de su historia, pero no determina el carácter de un individuo. Para convivir con uno sirven más sus experiencias, su salud y lo que observás en las situaciones de todos los días."),
      ("Juego con reglas que todos entiendan", "Puede entusiasmarse mucho con juguetes y persecuciones. Alterná juego activo con ejercicios breves de espera, olfato y momentos de calma; terminar antes de que se sobreexcite suele funcionar mejor que exigirle hasta agotarlo. Enseñá intercambios con premios en vez de quitarle objetos por la fuerza. Los juguetes deben resistir su mordida y revisarse si se rompen. Si hay niños, un adulto supervisa y le deja al perro un lugar donde retirarse."),
      ("Una casa que prevenga problemas", "Guardá comida, medicamentos y objetos pequeños fuera de alcance; la curiosidad puede llevarlo a explorar con la boca. Prepará paseos con correa cómoda y sitios donde pueda oler sin acercarse de golpe a otros animales. Reforzá conductas deseadas con constancia, sin castigos físicos. Un perro que se queda solo muchas horas puede necesitar un plan gradual de enriquecimiento, no una acumulación de juguetes. Contá en consulta si rompe objetos, cambia el apetito o aparece una conducta nueva."),
      ("Piel, oído y movimiento también cuentan", "Al cepillarlo, revisá piel, patas y orejas. En un manto blanco es fácil notar algunas irritaciones, pero un enrojecimiento persistente, mal olor o rascado no se resuelven suponiendo que es «alergia». Observá si oye y responde como siempre y si aparece dolor al levantarse o después de jugar. La revisión veterinaria ayuda a distinguir problemas de piel, oído o articulaciones y a elegir una pauta de cuidado, sin atribuir todo a la raza."),
      ("Cuándo conviene pedir una evaluación", "Anotá desde cuándo ocurre un cambio y en qué contexto: ¿sólo durante el juego, al tocar una zona, después de comer o también en reposo? Si ingiere un objeto, vomita repetidamente, tiene dificultad para respirar o dolor intenso, buscá atención urgente. Para molestias menos agudas, llevá videos breves y una lista de alimentos, premios y productos aplicados. Esos detalles hacen que la consulta se centre en lo que le pasa a tu bull terrier, no en una idea general de la raza."),
    ],
    [
      ("¿Es lo mismo que un pitbull?", "No. Son nombres e historias distintas. Incluso dentro de cada grupo, el cuidado debe partir del perro concreto y no de una etiqueta."),
      ("¿Puede vivir en un departamento?", "Puede hacerlo si tiene salidas, juego, descanso y una rutina que le permita bajar la intensidad. Los metros no sustituyen la actividad compartida."),
      ("¿Por qué tiene la cabeza así?", "La forma ovalada se consolidó en la selección histórica de la raza. No sirve por sí sola para evaluar su salud o temperamento."),
      ("¿Qué hago si muerde juguetes y traga partes?", "Retirá el objeto y consultá pronto; no provoques el vómito sin indicación. Para prevenir, elegí materiales adecuados y supervisá el juego."),
    ],
    [("AKC · historia del bull terrier", "https://www.akc.org/expert-advice/dog-breeds/bull-terrier-history/"),
     ("AKC · perfil de la raza", "https://www.akc.org/dog-breeds/bull-terrier/"), TRAINING],
    ("pitbull", "perro-mestizo"),
    ("¿Querés entender mejor su energía?", "Contanos cómo juega, descansa y se relaciona en casa."))

add("pequines", "Pequinés: pequeño heredero de una larga historia",
    "Origen del nombre, cuidado del manto y atención especial a respiración y ojos.", "27-pequines.webp",
    "El pequinés puede parecer un muñeco por su tamaño y pelo abundante. Es un perro con necesidades completas: caminar a su ritmo, elegir cuándo interactuar y estar cómodo al respirar, ver y moverse.",
    [
      ("Por qué se llama pequinés", "La raza se desarrolló como perro de compañía en la China imperial y su nombre remite a Pekín, hoy Beijing. El AKC documenta una historia muy antigua y su llegada posterior a Europa. Esa procedencia explica el nombre, pero no debería convertir al perro actual en un objeto decorativo: cada día necesita decisiones sobre paseos, abrigo, alimento, descanso y salud. Su tamaño chico no reduce la importancia de observar cambios de conducta."),
      ("Cepillar sin esconder la piel", "Separá el pelo para revisar detrás de orejas, cuello, axilas y patas, zonas donde pueden formarse nudos. Cepillá por tramos cortos y detenete si hay dolor. Un manto muy enredado requiere ayuda profesional; tirar para deshacerlo puede lastimar la piel. Después de salir, revisá si trae semillas, tierra o humedad. Si aparece olor, enrojecimiento o se rasca de forma persistente, la solución no es perfumarlo o bañarlo más seguido sin saber qué ocurre."),
      ("La respiración merece espacio en la consulta", "La cara corta puede asociarse con dificultad para mover aire. Mirá cómo respira dormido, en reposo y después de un paseo suave. Roncar o hacer ruido no demuestra que esté cómodo. Elegí horarios frescos, evitá el esfuerzo intenso y no lo dejes en un auto estacionado. Si jadea con gran esfuerzo, cambia el color de sus mucosas, se desploma o no logra recuperarse, buscá atención urgente. Una evaluación permite valorar su situación individual antes de una crisis."),
      ("Ojos y boca a su escala", "Sus ojos prominentes pueden lesionarse o irritarse; lagrimeo nuevo, ojo cerrado, secreción o dolor al tocar la cara merecen consulta. No apliques gotas humanas. En los controles incluí la boca: dientes pequeños no significan que la salud dental importe menos. Observá si mastica de un lado o deja caer alimento. Para jugar, preferí actividades de olfato y búsqueda a saltos desde muebles altos. Una casa a su escala puede darle autonomía sin exigirle un esfuerzo innecesario."),
      ("Qué datos ayudan cuando algo cambia", "Contá cuándo empezó la molestia, si ocurre con calor, después de comer o al dormir. Un video breve de la respiración en reposo o de cómo camina puede ser útil, siempre que grabarlo no demore la consulta. Llevá productos usados para piel y ojos, alimento y medicaciones. No atribuyas automáticamente la falta de ganas a «su carácter»: dolor, malestar ocular o respiratorio pueden cambiar su comportamiento."),
    ],
    [
      ("¿El pequinés necesita pasear?", "Sí, a una intensidad adecuada para su edad, cuerpo y respiración. También puede disfrutar juegos tranquilos dentro de casa."),
      ("¿Es normal que ronque?", "Puede ser frecuente, pero el ruido no permite descartar una obstrucción. Conviene evaluar cómo respira en reposo y con actividad."),
      ("¿Puedo cortarle todo el pelo en verano?", "Consultá antes de hacer un corte extremo. El objetivo es mantenerlo limpio y sin nudos, y reducir la exposición al calor con horarios y ambiente adecuados."),
      ("¿Qué hago si mantiene un ojo cerrado?", "Pedí atención veterinaria pronto. Evitá gotas oculares no indicadas y no intentes separar los párpados por la fuerza."),
    ],
    [("AKC · origen y cuidados del pequinés", "https://www.akc.org/dog-breeds/pekingese/"), BOAS],
    ("pug", "salud-dental-perros-gatos"),
    ("¿Tu pequinés cambió la forma de respirar?", "Describí el cambio; si le cuesta tomar aire, acudí a una guardia."))

add("border-collie", "Border collie: darle cauce a una mente siempre despierta",
    "Historia del perro pastor, actividad posible y señales de sobreexigencia.", "28-border-collie.webp",
    "El border collie no necesita vivir haciendo trucos, pero sí una vida con movimiento, aprendizaje y pausas. Su capacidad para prestar atención al entorno puede ser una alegría en casa si la rutina permite también descansar.",
    [
      ("La frontera que lleva en el nombre", "«Border» alude a la región fronteriza entre Escocia e Inglaterra donde se desarrollaron perros de pastoreo. El término «collie» se vinculó históricamente a perros de trabajo con ovejas. Se seleccionaron por su capacidad de conducir rebaños, no por tener un único aspecto; por eso pueden variar en pelo y color. Entender ese pasado ayuda a diseñar actividades que involucren cuerpo y atención, sin suponer que todos necesitan correr durante horas."),
      ("Un día con trabajo, juego y descanso", "Repartí la actividad en paseos, búsqueda de comida, aprendizaje de señales útiles y ratos tranquilos. Un circuito de olfato de diez minutos puede exigir más concentración que perseguir una pelota sin pausa. Observá si logra relajarse después: jadeo continuo, insistencia compulsiva o dificultad para dormir indican que conviene ajustar la propuesta. No hace falta convertir cada salida en entrenamiento; también necesita explorar, oler y estar con vos sin recibir órdenes."),
      ("Cuando intenta pastorear personas u objetos", "Algunos border collie persiguen bicicletas, corredores o a niños que se mueven rápido. No es una «maldad» ni conviene dejar que lo practique hasta que se intensifique. Usá distancia y correa para prevenir riesgos, reforzá que vuelva a mirarte y ofrecé alternativas de juego. Si la conducta es intensa o difícil de manejar, pedí orientación a un profesional que trabaje con métodos respetuosos. En casa, enseñá a los chicos a no correr alrededor del perro para provocarlo."),
      ("Cuidar el cuerpo que sostiene la actividad", "Antes de aumentar ejercicio, mirá edad, condición corporal y respuesta al día siguiente. Un cachorro en crecimiento, un adulto entrenado y un perro mayor necesitan ritmos distintos. Revisá almohadillas, uñas y piel después de salidas en terreno áspero. Si aparece cojera, rigidez, fatiga desproporcionada o evita un movimiento, detené la actividad exigente y consultá. La capacidad de aprender rápido no implica que el cuerpo tolere cualquier carga."),
      ("Hacer útil la consulta", "Llevá una descripción de horarios, tipo de ejercicio, sueño y alimento. Si te preocupa una conducta, anotá qué pasa justo antes y después, y en qué lugares ocurre. Un video breve puede mostrar el problema sin repetirlo a propósito. En la consulta pueden separar necesidades de actividad, dolor o estrés y armar un plan realista para tu casa. Una rutina buena es la que puede sostenerse en el tiempo y deja al perro cómodo."),
    ],
    [
      ("¿Necesita vivir en el campo?", "No necesariamente. Necesita actividad física y mental apropiada, convivencia y descanso; se puede planear una rutina urbana si la familia puede sostenerla."),
      ("¿La pelota alcanza como ejercicio?", "No conviene que sea la única actividad. Alterná olfato, paseos y aprendizaje; observá si logra bajar la intensidad."),
      ("¿Por qué fija la mirada o persigue movimientos?", "Su historia de pastoreo puede influir, pero el contexto importa. Si persigue bicicletas o niños, prevení riesgos y buscá orientación."),
      ("¿Cómo sé si está cansado de más?", "Cojea, tarda en recuperarse, duerme mal o evita actividades que antes disfrutaba: son motivos para revisar la rutina y su salud."),
    ],
    [("AKC · historia del border collie", "https://www.akc.org/expert-advice/dog-breeds/border-collie-history/"),
     ("AKC · perfil del border collie", "https://www.akc.org/dog-breeds/border-collie/"), TRAINING],
    ("malinois", "peso-saludable-mascotas"),
    ("¿Su energía se volvió difícil de encauzar?", "Contanos cómo son sus días y qué situaciones lo alteran."))

add("pug", "Pug: compañía pequeña, respiración que importa",
    "Su historia, sus pliegues y una rutina que respete su tolerancia al calor.", "29-pug.webp",
    "El pug suele buscar compañía y participar de todo. Para cuidarlo bien conviene mirar más allá de su expresión: cómo respira, cómo están sus ojos y cuánto esfuerzo tolera son preguntas de salud, no detalles estéticos.",
    [
      ("Un perro de compañía desde su origen", "Sus raíces están en China, donde se crió como perro de compañía hace muchos siglos; después llegó a distintas cortes europeas. El origen exacto del nombre inglés «pug» tiene varias explicaciones, así que es mejor no repetir una etimología como certeza. Su historia sí deja algo claro: fue seleccionado para vivir cerca de las personas. Eso no implica que deba seguirnos sin descanso; también necesita un sitio tranquilo donde dormir y retirarse."),
      ("Respirar cómodo no es un lujo", "La cara corta puede limitar la entrada de aire. Observá si hace ruido en reposo, duerme incómodo, se agota con poco ejercicio o tarda en recuperarse. El ronquido no sirve para declarar que todo está bien. Elegí paseos en horas frescas, llevá agua y evitá dejarlo en un vehículo estacionado. Si respira con esfuerzo marcado, se desploma o cambia el color de las encías, acudí a atención urgente. Una evaluación programada puede identificar problemas antes de una crisis."),
      ("Pliegues y ojos: mirar sin frotar", "Revisá los pliegues de la cara y observá si hay humedad, olor, enrojecimiento o molestia; pedí una pauta de limpieza individual en vez de aplicar cremas al azar. Sus ojos pueden lesionarse: si mantiene uno cerrado, lagrimea de golpe o parece dolerle, consultá pronto. No uses gotas humanas ni intentes retirar una posible lesión. Al jugar con otros perros, prestá atención a golpes de cara y elegí actividades que no lo obliguen a correr hasta quedar exhausto."),
      ("Peso y movimiento en pequeñas decisiones", "Puede disfrutar mucho la comida, pero los premios también suman. Anotá cuánto recibe de todas las personas de la casa y conversá sobre condición corporal en sus controles. Un paseo breve y regular, ajustado a su respiración y clima, es mejor que una salida larga que lo deje agotado. Si empieza a evitar escaleras o juegos, no supongas que está «perezoso»: puede haber dolor o dificultad respiratoria. El objetivo es que pueda moverse cómodo, no cumplir una cifra de pasos."),
      ("Cuándo consultar sin esperar", "Ante respiración dificultosa, desmayo, un ojo cerrado y doloroso o signos de golpe de calor, buscá asistencia de inmediato. Para cambios menos bruscos, llevá videos de cómo respira dormido o después de una actividad suave, junto con datos de comida, paseos y temperatura ambiental. No le des medicación humana para aliviarlo. La consulta puede ordenar qué es esperable para ese individuo y qué requiere un plan específico."),
    ],
    [("¿Es normal que ronque?", "Es frecuente, pero el ruido no descarta obstrucción. Si es intenso, nuevo o se acompaña de fatiga, merece evaluación."),
     ("¿Puede salir en verano?", "Sí, con horarios frescos y pausas, según su tolerancia. Evitá esfuerzos con calor y consultá ante signos de sobrecalentamiento."),
     ("¿Cómo cuido los pliegues?", "Pedí indicaciones para su piel concreta. Humedad, mal olor o dolor requieren revisión antes de usar productos."),
     ("¿Qué hago si cierra un ojo?", "Es motivo de consulta pronta. No apliques gotas no indicadas ni esperes varios días."),
     ("¿Los premios cuentan para su peso?", "Sí. Sumalos a la ración diaria y llevá una lista a los controles si el peso está cambiando.")],
    [("AKC · origen y salud del pug", "https://www.akc.org/dog-breeds/pug/"),
     ("AKC · historia del pug", "https://www.akc.org/expert-advice/dog-breeds/pug-history/"), BOAS],
    ("bulldog-frances", "golpe-de-calor-mascotas"),
    ("¿Te preocupa cómo respira tu pug?", "Si hay esfuerzo importante, acudí a una guardia sin esperar mensajes."))

add("bulldog-ingles", "Bulldog inglés: cuidar la comodidad detrás de los pliegues",
    "Origen del nombre, respiración, piel y movimientos de todos los días.", "30-bulldog-ingles.webp",
    "El bulldog inglés tiene una presencia inconfundible. La atención diaria no gira alrededor de su aspecto, sino de que pueda respirar con comodidad, caminar sin dolor y mantener la piel sana.",
    [
      ("El nombre conserva una historia que ya pasó", "La raza se desarrolló en Inglaterra y el término «bull» proviene de su relación histórica con la práctica cruel de enfrentar perros con toros. Esa actividad fue prohibida y el bulldog actual es un perro de compañía. Conocer la historia evita romantizarla y recuerda que una raza puede cambiar mucho de función. En casa importa el individuo: su forma de moverse, de descansar y de relacionarse, no una idea de fortaleza asociada a su silueta."),
      ("La respiración se evalúa, no se adivina", "Su hocico corto puede asociarse con dificultades respiratorias. Escuchá cómo respira dormido, en reposo y al caminar suave. Ronquidos, esfuerzo, intolerancia al ejercicio o recuperación lenta merecen una consulta. En días calurosos, elegí salidas cortas en horas frescas, agua y un sitio ventilado. Nunca lo dejes dentro de un auto. Si respira con gran esfuerzo, se desorienta o colapsa, acudí a una guardia: la falta de aire y el sobrecalentamiento no se resuelven por mensaje."),
      ("Pliegues limpios, piel observada", "Revisá si entre los pliegues hay humedad, olor, enrojecimiento o secreción. La pauta de limpieza y secado depende de la piel real del perro; frotar o aplicar productos perfumados puede empeorar una irritación. Mirá también debajo de la cola si tiene un pliegue marcado y prestá atención a si evita que toquen alguna zona. Una consulta permite distinguir irritación, infección u otro problema. No conviertas el cuidado de pliegues en una rutina dolorosa que deba tolerar a la fuerza."),
      ("Moverse sin cargar de más el cuerpo", "Aunque sea robusto, necesita movimiento compatible con su respiración, edad y articulaciones. Paseos regulares y tranquilos suelen ser más útiles que exigirle una salida intensa. Mantener una condición corporal adecuada puede mejorar su comodidad, pero no se logra con dietas bruscas. Si le cuesta levantarse, cojea o abandona un paseo que antes disfrutaba, anotá cuándo sucede y consultá. Un video caminando en línea recta puede ayudar al profesional sin forzarlo a repetir el movimiento."),
      ("Preguntas concretas para el control", "Llevá información sobre el sueño, tolerancia al calor, piel, peso y medicamentos o productos que usás. Preguntá qué señales requieren urgencia, qué actividad es apropiada y cómo cuidar sus pliegues sin lastimarlos. Si se plantea un procedimiento, comentá sus antecedentes respiratorios. Un buen plan no se copia de otro bulldog: se adapta a la evaluación de ese animal y a lo que la familia puede sostener."),
    ],
    [("¿Es lo mismo que un bulldog francés?", "No. Son razas distintas, con tamaño, historia y conformación diferentes, aunque ambas pueden presentar problemas respiratorios."),
     ("¿Puede hacer ejercicio?", "Sí, con intensidad y horarios acordes a su salud. Si se agota enseguida, hace mucho esfuerzo al respirar o cojea, consultá."),
     ("¿Debo limpiar cada pliegue todos los días?", "La frecuencia depende de su piel. Pedí una pauta individual y consultá si hay humedad, mal olor, dolor o secreción."),
     ("¿Es normal que jadee mucho?", "El jadeo puede tener varias causas. Si es intenso en reposo, aparece con poco esfuerzo o se acompaña de debilidad, necesita evaluación."),
     ("¿Puede dormir con ronquidos fuertes?", "El ruido no es una medida de bienestar. Mostrá un video al veterinario para valorar su respiración durante el descanso.")],
    [("AKC · historia del bulldog", "https://www.akc.org/expert-advice/dog-breeds/bulldog-history/"),
     ("AKC · perfil del bulldog", "https://www.akc.org/dog-breeds/bulldog/"), BOAS],
    ("bulldog-frances", "pug"),
    ("¿Hay algo en su respiración o piel que cambió?", "Anotá desde cuándo y busquemos una evaluación adecuada."))

add("american-bully", "American Bully: conocer al perro detrás de la silueta",
    "Historia propia, movimiento sin exageraciones y convivencia responsable.", "31-american-bully.webp",
    "El American Bully tiene una historia y un estándar propios. Su cuerpo puede ser compacto y musculoso, pero su bienestar se mide por lo que puede hacer cómodamente: respirar, caminar, jugar y descansar.",
    [
      ("Una raza distinta, un nombre explicable", "El United Kennel Club describe al American Bully como una raza desarrollada a partir de líneas de American Pit Bull Terrier, con influencia de otros perros tipo bulldog. Fue reconocido por el UKC en 2013. «Bully» alude a esa familia de perros, no es una predicción de agresividad. La selección ha producido tamaños y estructuras diferentes; por eso un nombre de raza no sustituye la evaluación individual de salud, temperamento y capacidad de movimiento."),
      ("Que pueda moverse vale más que impresionar", "El estándar del UKC advierte contra exageraciones corporales que interfieran con la actividad o la respiración. Observá cómo camina, sube un escalón, se incorpora y se recupera después de jugar. No confundas masa con condición física. Si cojea, se fatiga de manera marcada o respira con dificultad, pedí una revisión. El ejercicio se adapta a su cuerpo y al clima; no hace falta forzar saltos ni cargarle peso para que «se vea fuerte»."),
      ("Convivencia construida con experiencias", "Presentaciones graduales, paseos con correa y oportunidades de retirarse ayudan a cualquier perro. Enseñá señales útiles con recompensas y prepará encuentros con niños u otros animales bajo supervisión. Prestá atención a rigidez, evitación o cambios de expresión; respetar esas señales previene conflictos. Si aparece una conducta problemática, describí cuándo ocurre y buscá ayuda profesional. El tamaño de la cabeza o el ancho del pecho no permiten deducir cómo reaccionará en cada situación."),
      ("Piel, peso y vida cotidiana", "El pelo corto facilita mirar piel y patas después de paseos. En los controles conversá sobre condición corporal, movilidad y salud bucal. Si tiene pliegues o roces, observá humedad, irritación y dolor; no apliques cremas sin saber la causa. Repartí premios dentro de la comida del día y mantené actividad constante, no sólo esfuerzos intensos de fin de semana. Una rutina simple y sostenible ayuda más que perseguir una imagen corporal."),
      ("Qué llevar a la consulta", "Comentá edad, origen, alimentación, ejercicio, sueño, respiración y cualquier antecedente de lesión. Si notás que evita un movimiento, grabá un video sin obligarlo a repetirlo. Preguntá qué actividades son seguras para su estado actual y cómo reconocer sobrecalentamiento. La atención debe responder al perro que vive con vos, aunque otras personas tengan ideas fuertes sobre el aspecto o el nombre de la raza."),
    ],
    [("¿American Bully y pitbull son sinónimos?", "No. Comparten parte de su historia, pero el American Bully tiene desarrollo y estándar propios."),
     ("¿Necesita ejercicios de fuerza?", "No hay una obligación por su aspecto. Priorizá paseos, juego y movimiento cómodos; evitá cargas o esfuerzos sin evaluación."),
     ("¿Su cuerpo ancho dificulta respirar?", "No siempre, pero cualquier esfuerzo, ruido nuevo o recuperación lenta merece atención. El estándar también rechaza exageraciones que interfieran con respirar."),
     ("¿Cómo presentarlo a otro perro?", "Con distancia, correa, observación y posibilidad de retirarse. El éxito depende de ambos individuos y del contexto."),
     ("¿Cómo sé si tiene sobrepeso?", "La balanza sola no alcanza. En consulta pueden valorar condición corporal y músculo según su estructura real.")],
    [("UKC · estándar e historia del American Bully", "https://www.ukcdogs.com/breed-standards/american-bully"), TRAINING],
    ("pitbull", "peso-saludable-mascotas"),
    ("¿Querés revisar su movimiento o rutina?", "Contanos qué actividades disfruta y qué cambios notaste."))

add("malinois", "Pastor belga malinois: actividad con propósito y descanso real",
    "Qué significa su nombre y cómo organizar una vida que no sea sólo ejercicio.", "32-malinois.webp",
    "Un malinois puede aprender con rapidez y concentrarse mucho en una tarea. Esa capacidad pide una familia que pueda ofrecerle guía, actividades apropiadas y calma; cansarlo hasta el agotamiento no es un plan de cuidado.",
    [
      ("El nombre viene de una ciudad belga", "«Malinois» deriva de Malinas o Mechelen, ciudad de Bélgica asociada al desarrollo de esta variedad de pastor belga. Sus antepasados se seleccionaron para trabajar con ganado; después se emplearon en tareas muy distintas. La historia ayuda a entender su disposición para colaborar con personas, pero no define lo que cada perro sabe hacer ni cómo debe vivir. Un compañero de casa también necesita dormir, explorar y aprender a estar tranquilo sin una orden constante."),
      ("Un programa que incluya pausa", "Combiná paseos, olfato, entrenamiento breve y juegos que permitan terminar con calma. Aumentar la intensidad todos los días puede producir un perro cada vez más entrenado para exigir actividad, no necesariamente más satisfecho. Prepará un sitio de descanso y horarios previsibles. Si persigue sombras, gira sin parar o no puede relajarse, consultá antes de añadir más ejercicio. La calidad de las actividades y la posibilidad de recuperarse importan tanto como la duración."),
      ("Seguridad y aprendizaje temprano", "Su rapidez y capacidad de reacción hacen importante enseñar caminatas con correa, llamadas en lugares seguros y manejo cooperativo para revisiones. Evitá juegos que animen a morder manos o perseguir personas. Con niños y otros animales, supervisá siempre y permití distancia. La educación basada en recompensas y experiencias graduadas puede construir conductas fiables sin recurrir al miedo. Si una situación se vuelve difícil, pedí ayuda a un profesional que evalúe el caso y no aplique una receta de «perro de trabajo»."),
      ("El cuerpo también necesita seguimiento", "Revisá uñas, almohadillas, piel y peso después de actividades exigentes. Un cachorro, un adulto y un perro mayor toleran cargas distintas. Si cojea, se queda rígido después del descanso, pierde apetito o se fatiga de manera inesperada, suspendé el esfuerzo intenso y consultá. Llevá un registro de actividad de la última semana: es más útil que recordar sólo el día en que apareció el síntoma. No uses analgésicos humanos para que siga entrenando."),
      ("Una consulta orientada a su vida real", "Contá cómo transcurren sus días, dónde duerme, cuántas horas queda solo y qué ocurre antes de una conducta que te preocupa. Un video breve puede ayudar sin provocar la situación a propósito. El veterinario puede revisar salud y, si hace falta, orientar una derivación para conducta. La meta no es fabricar un atleta: es que ese perro pueda convivir y moverse de manera segura y disfrutable."),
    ],
    [("¿Malinois y pastor alemán son lo mismo?", "No. Tienen orígenes y conformación distintos, aunque ambos se criaron como perros de pastoreo y pueden disfrutar tareas compartidas."),
     ("¿Cuántas horas debe correr?", "No existe una cifra universal. La rutina combina movimiento, olfato, aprendizaje y descanso según edad y salud."),
     ("¿Puede vivir en una casa de ciudad?", "Puede, si la familia puede ofrecerle una rutina sostenida y un entorno seguro. El tamaño del patio no resuelve por sí solo sus necesidades."),
     ("¿Qué hago si no logra relajarse?", "Registrá cuándo ocurre, revisá sueño y rutina y pedí orientación. Añadir ejercicio sin entender la causa puede no ayudar."),
     ("¿Es necesario usar castigos fuertes?", "No. Hay enfoques basados en recompensas y manejo del entorno que priorizan aprendizaje y bienestar.")],
    [("AKC · historia del malinois", "https://www.akc.org/expert-advice/dog-breeds/belgian-malinois-history/"),
     ("AKC · perfil del malinois", "https://www.akc.org/dog-breeds/belgian-malinois/"), TRAINING],
    ("border-collie", "pastor-aleman"),
    ("¿Necesitás ordenar su rutina?", "Contanos cómo son sus días, incluido el descanso."))

add("pastor-aleman", "Pastor alemán: del trabajo con ovejas a la vida en familia",
    "Origen de su nombre, actividad, aprendizaje y atención a la movilidad.", "33-pastor-aleman.webp",
    "Conocido por aprender y acompañar, el pastor alemán es también un perro grande con necesidades concretas de movimiento, descanso y controles. Ni el prestigio de la raza ni una foto dicen cómo está ese individuo.",
    [
      ("Un nombre que cuenta su primer trabajo", "Se formó a partir de perros de pastoreo de distintas regiones de Alemania. A fines del siglo XIX, criadores como Max von Stephanitz impulsaron un tipo reconocido por su capacidad de trabajo; «pastor alemán» conserva ese origen. Después la raza se hizo conocida en muchos roles, pero la vida de un perro de familia se construye en casa. Conocer su historia ayuda a comprender por qué puede disfrutar tareas y aprendizaje, sin exigirle que actúe como un perro de servicio."),
      ("Moverse con una progresión razonable", "Necesita salidas y oportunidades de usar el cuerpo, pero la intensidad cambia con la edad, la condición física y el clima. En cachorros evitá imponer saltos repetidos o ejercicio muy exigente; en adultos observá recuperación y comodidad al día siguiente. Intercalá olfato, caminatas y descansos. Si se levanta con dificultad, cojea o cambia la forma de sentarse, anotá cuándo ocurre y pedí una evaluación. El tamaño y la capacidad de aprender no lo vuelven inmune al dolor."),
      ("Aprender a convivir, no sólo a obedecer", "Practicar caminar con correa, esperar ante una puerta y aceptar una revisión puede servir más a diario que una lista larga de trucos. Exponelo de forma gradual a personas, sonidos y lugares; la socialización no significa forzarlo a saludar a todos. Si se muestra incómodo, aumentá distancia y observá. Con niños y otros animales, supervisá las interacciones. La educación con recompensas ayuda a construir respuestas previsibles sin basarse en intimidación o castigos."),
      ("Pelo, piel y peso", "Su manto puede soltar abundante pelo; cepillarlo de manera regular ayuda a retirar el suelto y permite ver irritaciones o parásitos. No uses el cepillado para ocultar una picazón que persiste. Registrá peso y condición corporal en los controles: el exceso de peso suma carga a un cuerpo grande. Revisá también boca y uñas. Si aparecen zonas sin pelo, mal olor en piel u oído o un cambio de apetito, no lo atribuyas sólo a la estación del año."),
      ("Preparar una consulta que responda preguntas", "Llevá antecedentes, alimento, medicaciones y una descripción de actividad normal. Un video corto de cómo camina puede mostrar una dificultad que en el consultorio no aparezca; no lo obligues a repetir un salto doloroso. Preguntá por controles apropiados a su edad y por una rutina posible para la familia. El plan se ajusta al perro que vive con vos, no al trabajo histórico de la raza."),
    ],
    [("¿Debe entrenar todos los días?", "Le hace bien aprender y tener una rutina, pero el entrenamiento puede ser breve e incluir descanso y juego."),
     ("¿La cojera es normal por ser grande?", "No. Si cojea, se levanta con dificultad o evita movimientos, conviene una evaluación."),
     ("¿Puede vivir con niños?", "La convivencia depende de las experiencias de todos y requiere supervisión. Ninguna raza reemplaza la enseñanza de interacciones respetuosas."),
     ("¿Hace falta un jardín?", "Un jardín no sustituye paseos, olfato y tiempo compartido. La rutina importa más que una superficie por sí sola."),
     ("¿Por qué pierde tanto pelo?", "La muda puede ser normal, pero picazón, zonas peladas, olor o enrojecimiento merecen consulta.")],
    [("AKC · historia del pastor alemán", "https://www.akc.org/expert-advice/dog-breeds/german-shepherd-dog-history/"),
     ("AKC · perfil del pastor alemán", "https://www.akc.org/dog-breeds/german-shepherd-dog/"), TRAINING],
    ("malinois", "peso-saludable-mascotas"),
    ("¿Cambió su manera de caminar?", "Un video y la fecha de inicio pueden ayudar a orientar el control."))

add("galgo-espanol", "Galgo español: calma en casa, seguridad al salir",
    "La historia de un lebrel, paseos con criterio y cuidados para un cuerpo singular.", "34-galgo.webp",
    "El galgo español suele llamar la atención por su silueta fina. Es importante conocer su cuerpo y su historia sin convertirlos en estereotipos: puede disfrutar carreras seguras y también muchas horas de descanso.",
    [
      ("Galgo español, una raza con origen propio", "La Federación Cinológica Internacional reconoce al galgo español como raza originaria de España, dentro del grupo de lebreles. Su nombre indica esa procedencia; no debe confundirse automáticamente con el greyhound inglés, aunque comparten el tipo de perro de vista y carrera. Históricamente se usó para perseguir presas, pero un galgo que vive en casa necesita un plan actual de convivencia, no una vida definida por el pasado de la raza."),
      ("Pasear con seguridad antes que con prisa", "Puede reaccionar muy rápido ante algo que se mueve. En espacios abiertos, usá una correa y un equipo bien ajustado; soltalo sólo en un lugar seguro y cerrado si su conducta y el contexto lo permiten. Las salidas pueden combinar caminata, olfato y oportunidades de correr controladas. No pruebes la llamada por primera vez frente a un estímulo intenso. Si fue adoptado recientemente, conocé su respuesta de a poco antes de cambiar horarios, rutas o compañeros de paseo."),
      ("Un cuerpo fino que merece buen descanso", "Su silueta naturalmente delgada no permite decidir el peso saludable sólo mirando costillas. El veterinario puede valorar condición corporal y musculatura para ese individuo. Ofrecé una superficie de descanso cómoda y observá si aparecen rozaduras o zonas dolorosas. Después de una carrera, revisá uñas, almohadillas y pequeñas heridas. Si cojea, pierde peso, cambia el apetito o se muestra rígido, consultá: no todo se explica porque «es un galgo»."),
      ("Conocer su pasado sin forzar confianza", "Algunos galgos llegan a una casa después de experiencias previas desconocidas. Una rutina previsible, un refugio tranquilo y la posibilidad de acercarse a su ritmo ayudan más que exigir contacto inmediato. Presentá a otros animales gradualmente y supervisá; el impulso de perseguir puede variar entre individuos. Si se sobresalta, se congela o evita ciertas situaciones, anotá el contexto y buscá orientación respetuosa. No confundas quietud con comodidad."),
      ("Qué observar antes de una visita", "Llevá información sobre origen conocido, vacunas, alimentación, actividad y cualquier lesión previa. Contá si duerme tranquilo, cómo se recupera después de correr y si cambió la forma de caminar. Si encontraste una herida profunda, dolor intenso o dificultad para respirar, necesitás atención pronta. En controles habituales pueden acordar actividad y peso adecuados sin imponer una idea genérica de «perro de carrera»."),
    ],
    [("¿Galgo español y greyhound son idénticos?", "No. Son razas diferentes de lebreles; el galgo español está reconocido como raza de origen español."),
     ("¿Tiene que correr todos los días?", "No existe una cuota universal. Necesita actividad apropiada y oportunidades seguras para moverse, además de descanso."),
     ("¿Es normal que se le marquen las costillas?", "La silueta fina puede ser normal, pero el peso saludable se valora con condición corporal, músculo e historia de ese perro."),
     ("¿Puedo soltarlo en una plaza abierta?", "No conviene asumir que volverá al llamarlo frente a estímulos de movimiento. Elegí espacios seguros y cerrados."),
     ("¿Cómo ayudo a un galgo recién adoptado?", "Dale horarios previsibles y tiempo para explorar a su ritmo. Si muestra miedo intenso, consultá por un plan individual.")],
    [("FCI · estándar del galgo español", "https://www.fci.be/es/nomenclature/GALGO-ESPANOL-285.html"),
     ("FCI · estándar completo del galgo español", "https://www.fci.be/Nomenclature/Standards/285g10-en.pdf"), TRAINING],
    ("perro-mestizo", "pulgas-y-garrapatas"),
    ("¿Acaba de llegar un galgo a tu casa?", "Contanos lo que sabés de él y cómo son sus primeras semanas."))

add("doberman", "Dóberman: el nombre de una persona, la vida de un perro",
    "Historia alemana, aprendizaje cotidiano y controles para acompañar su actividad.", "35-doberman.webp",
    "Su porte elegante puede dar una impresión de seguridad absoluta. Un dóberman también puede sentir dolor, cansancio o miedo: la mejor convivencia nace de conocer su respuesta individual y ofrecer una rutina clara.",
    [
      ("Louis Dobermann y el origen del nombre", "La raza se desarrolló en Alemania a fines del siglo XIX y lleva el apellido de Karl Friedrich Louis Dobermann, que buscó un perro capaz de acompañarlo y protegerlo. Las combinaciones exactas de razas usadas no están documentadas con certeza. Ese origen no convierte a todo dóberman en guardián ni indica cómo tratarlo: un perro de familia necesita experiencias graduales, juego, descanso y una relación que no dependa de intimidarlo."),
      ("Movimiento con objetivos posibles", "Es un perro atlético que puede disfrutar paseos, aprendizaje y actividades compartidas. Aumentá la intensidad de forma progresiva, especialmente si pasó un tiempo sin ejercicio. Alterná movimiento con olfato y descanso. Si se fatiga inesperadamente, tose, se desmaya, evita caminar o cojea, suspendé la actividad y consultá. Un cuerpo que parece fuerte no justifica ignorar señales; en los controles preguntá qué seguimiento corresponde a su edad y antecedentes."),
      ("Un perro atento también necesita previsibilidad", "Enseñá a caminar con correa y a aceptar revisiones de patas, boca y orejas mediante pasos pequeños y recompensas. Presentá personas y lugares sin forzar saludos. Si reacciona ante visitas o perros, registrá distancia, contexto y señales previas. Castigos o provocaciones pueden empeorar una situación. Con niños, establecé reglas de interacción y un sitio al que el perro pueda retirarse; la vigilancia de un adulto sigue siendo necesaria aunque haya vivido siempre en familia."),
      ("Pelo corto, piel visible y condición corporal", "El manto corto facilita detectar roces o lesiones, pero no reemplaza una revisión. Mirá almohadillas, uñas y piel después de actividades. Registrá peso y alimento, incluyendo premios. Una caída de energía, pérdida de peso o cambios de apetito justifican consulta aun si el pelo luce bien. Preguntá por controles preventivos apropiados y no te guíes sólo por consejos de otros dueños: la historia clínica y la exploración de ese dóberman son la base."),
      ("Una consulta mejor preparada", "Llevá un registro breve de actividad, sueño, alimentación y cualquier síntoma, con fecha de inicio. Si hubo desmayo o una respiración distinta, contalo aunque haya durado poco; no vuelvas a exigir ejercicio para «comprobar» si se repite. Un video espontáneo puede ayudar si no retrasa la asistencia. Preguntá qué señales requieren guardia y cuándo volver a controlar. Tener un plan claro reduce la tentación de atribuir todo al carácter de la raza."),
    ],
    [("¿Dóberman y dóberman pinscher son lo mismo?", "Sí. Son formas de nombrar la misma raza; en distintos lugares se usa o se omite «pinscher»."),
     ("¿Hay que cortarle las orejas?", "No. Un dóberman puede conservar sus orejas naturales; la apariencia no define su capacidad de aprender o convivir."),
     ("¿Puede vivir con niños?", "La convivencia depende de experiencias y supervisión. Enseñá a todos a respetar el descanso y las señales del perro."),
     ("¿Cuándo preocuparse por el cansancio?", "Fatiga nueva o desproporcionada, tos, desmayo o dificultad para respirar requieren evaluación veterinaria."),
     ("¿Necesita entrenamiento de protección?", "No para ser un compañero de familia. La educación cotidiana, el manejo seguro y la relación respetuosa son prioritarios.")],
    [("AKC · historia del dóberman", "https://www.akc.org/expert-advice/dog-breeds/doberman-pinscher-history/"),
     ("AKC · perfil del dóberman", "https://www.akc.org/dog-breeds/doberman-pinscher/"), TRAINING],
    ("pastor-aleman", "salud-dental-perros-gatos"),
    ("¿Notaste un cambio en su energía?", "Describí cuándo apareció y cómo se recupera después de moverse."))

add("boxer", "Bóxer: juego, fuerza y descansos bien pensados",
    "Una raza desarrollada en Alemania y una rutina que cuide su cuerpo activo.", "36-boxer.webp",
    "El bóxer suele llamar a jugar con todo el cuerpo. Conviene acompañar ese entusiasmo con movimiento apropiado, pausas y atención a cambios de respiración o energía, en vez de esperar a que siempre siga el mismo ritmo.",
    [
      ("De dónde viene el bóxer", "La raza moderna se desarrolló en Alemania entre fines del siglo XIX y comienzos del XX, a partir de perros de trabajo de esa región. La explicación popular de su nombre lo relaciona con la forma de usar las patas delanteras al jugar, como si «boxeara»; es una interpretación difundida, no una pauta para entender su carácter. Conocer la historia puede ser curioso, pero el cuidado actual depende de la edad, salud y vida del perro que tenés en casa."),
      ("Jugar sin pasarse de rosca", "Alterná paseos, búsqueda y juegos breves con momentos de descanso. Un bóxer puede seguir pidiendo actividad aun cuando está cansado; observá jadeo, coordinación y recuperación. Evitá ejercicio intenso en calor y ofrecé agua y sombra. Un cachorro no necesita saltos repetidos para «gastar energía». Enseñá a soltar juguetes y a saludar sin empujar, usando recompensas y prácticas cortas. Con niños, supervisá el juego y evitá que ambos se sobreexciten."),
      ("Preguntar también por el corazón", "En sus controles, comentá si tose, se fatiga con una actividad que antes toleraba, parece débil o se desmaya. El AKC señala que la raza puede presentar problemas cardíacos entre otras condiciones; eso no significa que todo bóxer vaya a desarrollarlos. La historia clínica y el examen orientan si hacen falta estudios. Un desmayo o dificultad respiratoria requieren atención urgente. No lo pongas a correr de nuevo para ver si el episodio se repite."),
      ("Pelo corto no equivale a cero cuidados", "El cepillado suave permite revisar piel, bultos, irritaciones y parásitos. Mirá también orejas, patas y boca, y anotá cambios que persistan. Su tolerancia a extremos de calor y frío puede ser limitada, por lo que conviene adaptar horarios y ambiente. Registrá peso y premios: un cuerpo musculoso no permite evaluar condición corporal sólo con la balanza. Si evita saltar, cojea o parece dolorido al incorporarse, consultá antes de aumentar actividad."),
      ("Llevar una historia breve a la visita", "Contá cómo juega, cuánto tarda en recuperarse, qué come y si hubo tos, desmayo o cambios de apetito. Una fecha de inicio y un video espontáneo ayudan más que descripciones como «está raro», siempre que no retrases la asistencia para grabar. Pedí que te indiquen qué signos observar hasta el próximo control. El objetivo es preservar la alegría de moverse sin pasar por alto molestias o señales de enfermedad."),
    ],
    [("¿Por qué se llama bóxer?", "Una explicación conocida vincula el nombre con el juego usando las patas delanteras; su origen como raza moderna está en Alemania."),
     ("¿Necesita correr todos los días?", "No hay una medida universal. Conviene una actividad regular adaptada a edad, clima, condición corporal y salud."),
     ("¿Qué hago si se desmaya?", "Es una urgencia veterinaria. No lo fuerces a seguir caminando y contá qué ocurrió antes del episodio."),
     ("¿Es normal que jadee después de jugar?", "Puede jadear, pero un esfuerzo excesivo, recuperación lenta, debilidad o dificultad para respirar requieren evaluación."),
     ("¿El pelo corto necesita cepillado?", "Sí, de forma sencilla: ayuda a retirar pelo suelto y a revisar la piel.")],
    [("AKC · perfil y salud del bóxer", "https://www.akc.org/dog-breeds/boxer/"),
     ("AKC · historia del bóxer", "https://www.akc.org/expert-advice/dog-breeds/boxer-history/"),
     ("AKC · historia del nombre", "https://www.akc.org/expert-advice/lifestyle/fun-facts-boxer/")],
    ("doberman", "golpe-de-calor-mascotas"),
    ("¿Cambió su energía al jugar?", "Contanos cuándo ocurre y si aparece tos o fatiga."))

add("bichon-frise", "Bichón frisé: rulos blancos y una historia viajera",
    "Qué significa el nombre, cómo cuidar su pelo y por qué también necesita paseo.", "37-bichon-frise.webp",
    "El bichón frisé es pequeño y esponjoso, pero su cuidado no termina en el peinado. Necesita moverse, explorar, descansar y tener una piel y una boca revisadas con tanta atención como un perro grande.",
    [
      ("Un nombre que habla del pelo", "El bichón pertenece a una familia histórica de pequeños perros blancos de compañía; el AKC vincula su desarrollo moderno con el área mediterránea y Tenerife. «Frisé» alude al pelo rizado. A través de distintas épocas pasó de ambientes cortesanos a hogares comunes, conservando su papel de compañero. Esa historia explica el nombre y su aspecto, pero no reduce sus necesidades actuales a quedarse en brazos o posar para una foto."),
      ("Cepillar para que pueda estar cómodo", "Separá el pelo por capas y revisá axilas, orejas, cuello y zona bajo la cola, donde pueden esconderse nudos. Un enredo pegado a la piel puede tirar al caminar o al mover la cabeza; si duele, pedí ayuda profesional en vez de cortar cerca de la piel con tijeras. Planificá baños y cortes según el manto real y la rutina de la familia. Enrojecimiento, olor o rascado persistente merecen consulta antes de probar productos perfumados."),
      ("Tener juegos y paseos a su tamaño", "Un perro chico puede disfrutar caminatas, olfato y aprendizaje. Ofrecé oportunidades de explorar el suelo a su ritmo; llevarlo siempre en brazos le quita esas experiencias. En días calurosos revisá el pavimento y adaptá horarios. Enseñá a visitas y niños a esperar que se acerque, sin levantarlo de sorpresa. Si se resiste a salir, observá si hay dolor en patas, boca o articulaciones en vez de atribuirlo automáticamente a «mañas»."),
      ("Ojos, boca y peso bajo el pelo", "Mirá si hay lagrimeo nuevo, un ojo cerrado o irritación de piel bajo las zonas húmedas de la cara. No uses gotas o productos blanqueadores cerca de los ojos sin indicación. Revisá mal aliento persistente, encías y manera de masticar en los controles. El manto voluminoso puede ocultar cambios de peso; la evaluación corporal permite saber mejor cómo está. Si aparece apatía, menos apetito o un cambio en el juego, anotá cuándo comenzó."),
      ("Preparar una rutina sostenible", "El mejor plan de cepillado es el que el perro tolera y la familia puede mantener. Dividí las sesiones, premiá la cooperación y dejá una zona tranquila para descansar. En consulta, contá frecuencia de grooming, alimento, productos de piel y cambios observados. Si el pelo está muy anudado o la piel lesionada, la prioridad es resolver la molestia con seguridad, no conservar una forma de corte. La belleza del manto debe acompañar su bienestar."),
    ],
    [("¿Bichón frisé y caniche son la misma raza?", "No. Comparten pelo rizado y necesidades de cepillado, pero tienen historias y estándares distintos."),
     ("¿Necesita pasear si es tan pequeño?", "Sí. El paseo aporta movimiento, olores y experiencias; la duración se adapta a su edad y salud."),
     ("¿El pelo blanco requiere productos especiales?", "Lo importante es mantener piel y manto limpios y sin nudos. Pedí una pauta antes de usar cosméticos cerca de ojos o piel irritada."),
     ("¿Cada cuánto se corta el pelo?", "Depende del crecimiento y de cuánto se cepilla en casa. Un profesional puede ayudar a fijar una frecuencia cómoda."),
     ("¿Qué hago con manchas bajo los ojos?", "Si el lagrimeo es nuevo, hay dolor o enrojecimiento, consultá antes de intentar blanquear la zona.")],
    [("AKC · perfil e historia del bichón frisé", "https://www.akc.org/dog-breeds/bichon-frise/"),
     ("AKC · historia del bichón frisé", "https://www.akc.org/expert-advice/dog-breeds/bichon-frise-history/")],
    ("caniche", "salud-dental-perros-gatos"),
    ("¿El cepillado ya le resulta incómodo?", "Contanos dónde aparecen nudos o irritación."))

add("shar-pei", "Shar-pei: el perro de «piel de arena»",
    "Origen de su nombre, pliegues, ojos y convivencia sin estereotipos.", "38-shar-pei.webp",
    "Los pliegues de un shar-pei son reconocibles al instante. Para cuidarlo bien hay que mirar la piel que queda debajo, los ojos, la comodidad al moverse y la manera en que vive las situaciones de cada día.",
    [
      ("Qué quiere decir shar-pei", "Es una raza originaria de China. El nombre se traduce habitualmente como «piel de arena» y alude a la textura áspera de su manto, no sólo a sus arrugas. El AKC describe una larga historia y un período en que la raza llegó a ser poco frecuente. Esa historia es interesante, pero no convierte los pliegues en una meta de crianza: el bienestar exige que pueda ver, respirar y moverse cómodamente."),
      ("La piel se observa sin frotar", "Mirá entre pliegues si hay humedad, mal olor, enrojecimiento, dolor o secreción. No hace falta aplicar cremas, talcos o productos perfumados por rutina; si hay irritación, el veterinario debe indicar cómo tratarla. Al secarlo después de un baño, comprobá que no queden zonas húmedas sin provocar fricción. Revisá también patas y zonas donde el pelo roza. Si se rasca de forma insistente o evita el contacto, pedí una evaluación en vez de asumir que «siempre fue así»."),
      ("Ojos y oídos merecen controles", "La forma de los párpados y los pliegues alrededor de los ojos pueden generar molestias en algunos individuos. Si mantiene un ojo cerrado, lagrimea, se frota la cara o aparece una secreción nueva, consultá pronto; no uses gotas humanas. Prestá atención también a sacudidas de cabeza, olor o dolor en orejas. Limpiar por tu cuenta un oído inflamado puede empeorar el problema. En los controles, pedí que revisen ojos y oídos aunque no notes una lesión grande."),
      ("Convivencia que permita elegir distancia", "Presentá personas y perros de a poco, sin forzar saludos. Enseñá señales simples con recompensas y ofrecé un lugar donde retirarse. Si se queda rígido, se aleja o muestra incomodidad, respetá la señal antes de que la situación escale. Un perro reservado no necesita que cada visita lo toque. Si cambia de carácter de manera repentina, considerá también dolor de piel, ojos u oídos: la salud y la conducta pueden estar relacionadas."),
      ("Qué información sirve en la consulta", "Anotá desde cuándo apareció un problema, qué producto se aplicó y si coincide con baño, calor o paseo. Una foto de la zona puede ayudar, pero no reemplaza examinarla. Si hay fiebre, decaimiento marcado, un ojo doloroso o dificultad para respirar, buscá atención sin esperar. En esta raza, episodios repetidos de fiebre con articulaciones dolorosas o hinchadas pueden relacionarse con un síndrome inflamatorio hereditario y merecen estudio; no todo episodio de fiebre tiene esa causa. Preguntá cómo cuidar la piel y qué controles son adecuados para tu perro: copiar una rutina ajena puede retrasar un diagnóstico."),
    ],
    [("¿El nombre significa «perro arrugado»?", "No exactamente. Suele traducirse como «piel de arena», por la textura áspera del manto."),
     ("¿Hay que limpiar cada pliegue todos los días?", "No existe una frecuencia universal. Observá la piel y pedí una pauta individual; humedad, olor o dolor requieren revisión."),
     ("¿Qué hago si cierra un ojo?", "Consultá pronto. Puede haber dolor ocular; evitá gotas no indicadas."),
     ("¿Puede convivir con otros perros?", "Depende de los individuos y de las presentaciones. Hacelas graduales y supervisadas, sin forzar contacto."),
     ("¿Las arrugas indican que está sano?", "No. La apariencia no sustituye revisar piel, ojos, respiración y movilidad."),
     ("¿Qué pasa si tiene fiebre varias veces?", "Registrá cada episodio y consultá. La fiebre recurrente con articulaciones hinchadas puede requerir estudiar una condición propia de la raza, además de descartar otras causas.")],
    [("AKC · origen y características del shar-pei", "https://www.akc.org/dog-breeds/chinese-shar-pei/"),
     ("AKC · significado del nombre", "https://www.akc.org/expert-advice/lifestyle/7-things-you-didnt-know-about-the-chinese-shar-pei/"),
     ("Manual MSD · fiebre del Shar-pei", "https://www.merckvetmanual.com/es-us/sistema-inmunitario/enfermedades-inmunol%C3%B3gicas/fiebre-del-shar-pei"), TRAINING],
    ("bulldog-ingles", "salud-dental-perros-gatos"),
    ("¿Le molesta la piel o mantiene un ojo cerrado?", "Contanos lo que viste; el dolor ocular requiere consulta pronta."))
